### ISSUE TITLE
Performance regression of `atomic_ref` due to extra local store

### ISSUE THREAD

**Issue by PointKernel** [NVIDIA/cccl#1008]
When benchmarking `atomic_ref::compare_exchange_strong` against `atomic::compare_exchange_strong`, we noticed that the former is always slower.

Here is the isolated repro: https://godbolt.org/z/xzcjhY84W

Compared to `atomic`, `atomic_ref` generates an extra `STL` SASS instruction. It's been confirmed that by replacing `atomic_ref::compare_exchange_strong` with `atomicCAS`, we can get about the same performance as `atomic::compare_exchange_strong` so the extra local store is indeed the culprit.

![image](https://user-images.githubusercontent.com/12716979/219145556-e7da557f-bb6a-4684-be31-c26024b035c3.png)
NCU shows the `STL` seems to come from member init in `__atomic_base_storage` ctor.
```[tasklist]

```

**Comment by ahendriksen** [comment]
Seems to be an issue related to volatile pointer dereference. I have traced the different code paths taken by atomic ref and atomic here: https://github.com/ahendriksen/cccl/commit/c9756c0d4c477e66d4d38a22cddfdf4ff6c7bf61

**Comment by ahendriksen** [comment]
The fix is to add non-volatile overloads: https://github.com/NVIDIA/cccl/commit/6892523fe82b03e7f0e6978734e19947a016b35d

**Comment by ahendriksen** [comment]
Thanks to @wmaxey PR #1582, the code example does not produce local stores anymore. I confirmed this locally. 

[In this CE link](https://godbolt.org/z/sPqs6qrWG), I have added CCCL trunk as library, but it does not yet seem to have incorporated the latest changes.I expect the fix will reflect there shortly as well.

@PointKernel, can you check if the latest PR fixes your issue?

**Comment by PointKernel** [comment]
Thanks for the updates.

Our project, [cuCollections](https://github.com/NVIDIA/cuCollections) is using `rapids-cmake` for dependency control and bumping the CCCL version to the latest in `rapids-cmake` requires non-trivial effort. Would this change be backported to CCCL 2.2 or 2.3?

**Comment by jrhemstad** [comment]
> Would this change be backported to CCCL 2.2 or 2.3?

No. We don't backport features to older releases. It will require updating to a newer version of CCCL.

**Comment by PointKernel** [comment]
> > Would this change be backported to CCCL 2.2 or 2.3?
> 
> No. We don't backport features to older releases. It will require updating to a newer version of CCCL.

Got it, thanks!

Will keep you posted on the verification. Closing this issue for now.
