### ISSUE TITLE
Add standardized extended floating point types with complete implementations

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1011]
As a CUDA user, I care about extended floating point types like `__half` or `__nv_bfloat16`. These types are deficient in a variety of ways as they may be lacking certain functionality one would expect from such a type.

We should add equivalent types to libcu++ that have both host and device implementations. 

Ideally, these should provide seamless transition to a built-in compiler provided type such that if I write my code using `cuda::float16` that it will use the built-in type when available and fall back to a library implementation if not.

CUTLASS has [implementations](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/half.h) that we should use as a starting point. 

See also: 
- https://github.com/NVIDIA/libcudacxx/issues/95
- https://github.com/NVIDIA/cccl/issues/987

```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/1451
- [ ] https://github.com/NVIDIA/cccl/issues/1452
```

**Comment by cliffburdick** [comment]
In the [MatX](https://github.com/NVIDIA/MatX) we had to create our own wrappers to support `__half`, and `__nv_bfloat16` types with wrappers so all normal C++ math operations are supported. It would be very useful if we could drop our types and use a standard version.

**Comment by miscco** [comment]
@cliffburdick if you drop me a link I am happy to do the leg work of porting those

**Comment by jrhemstad** [comment]
> @cliffburdick if you drop me a link I am happy to do the leg work of porting those

To be clear, we won't just be trivially porting the MatX types. We'd need to evaluate the diff between CUTLASS, MatX, and the various other solutions to design a standard solution and then build that.

**Comment by cliffburdick** [comment]
@miscco our half file is here: https://github.com/NVIDIA/MatX/blob/main/include/matx/core/half.h
half complex is here: https://github.com/NVIDIA/MatX/blob/main/include/matx/core/half_complex.h

I agree they should not be ported as-is. I don't know if the CUTLASS ones contain all the stuff we have, but I think the end goal would be once `cuda::` has the types we can alias them using our old names and delete the files.

**Comment by jrhemstad** [comment]
Closing this as superseded by https://github.com/NVIDIA/cccl/issues/1665
