### ISSUE TITLE
Compilation error when using in NVRTC with nvc++ as C++ compiler

### ISSUE THREAD

**Issue by jszuppe** [NVIDIA/cccl#1012]
```
#include <cuda/std/climits>

constexpr double a = __DBL_DENORM_MIN__;
using T = decltype(a);
```

When I compile the code presented above with NVRTC and `nvc++` (23.1) as C++ compiler I'm getting:

```
test_kernel.cu(4): error: floating constant is out of range
  constexpr double a = __DBL_DENORM_MIN__;
```

Reproducer and compilation command in the gist: https://gist.github.com/jszuppe/79645a85a442cc0c46556d1aadc5c782

What's funny is that when I use `g++`/`clang` or older `nvc++` (21.1) as C++ compiler it works fine. Same goes for the mentioned code and `nvcc`.

**Comment by jrhemstad** [comment]
This is now tracked by https://github.com/NVIDIA/cccl/issues/1177
