### ISSUE TITLE
Potentially unnecessary acquire barrier in benchmarks/concurrency.cpp:ticket_mutex

### ISSUE THREAD

**Issue by hernanponcedeleon** [NVIDIA/cccl#1027]
I believe there is no need to make [the RMW](https://github.com/NVIDIA/libcudacxx/blob/75de028b60397e5ec16073e3b538f329e5f33a89/benchmarks/concurrency.cpp#L154) in the `lock()` method an acquire one.

Except the following load, I think any other instruction will be ordered after the RMW due to the control dependency introduced by the `if(now == my)`. While it is possible to reorder the load and the RMW, I don't think this affects correctness of the code.

I wrote a small litmus tests and run it wrt PTX memory consistency (which should be close enough to CUDA) with two tools
- The tool from [here](https://github.com/NVlabs/mixedproxy) by @daniellustig using this code
```
.global x; // non atomic variable
.global y; // in
.global z; // out

d0.b0.t0 {
  // Acquire lock
  atom.add.relaxed.gpu r1, [y], 1; // This one was relaxed
  ld.acquire.gpu r2, [z];
  // Critical section
  ld.weak r3, [x];
  st.weak [x], 1;
  // Release lock
  atom.add.release.gpu r4, [z], 1;
}

d0.b0.t1 {
  // Acquire lock
  atom.add.relaxed.gpu r11, [y], 1; // This one was relaxed
  ld.acquire.gpu r12, [z];
  // Critical section
  ld.weak r13, [x];
  st.weak [x], 1;
  // Release lock
  atom.add.release.gpu r14, [z], 1;
}

permit (r1 == r2 && r11 == r12 && r3 == 0 && r13 == 0) as outcome;
```
While the tool does not support conditionals, the test should show the overall behavior. Conditions `r1 == r2` and `r11 == r12` guarantee each call to the lock method succeeded. Conditions `r3 == 0` and `r13 == 0` check if mutual exclusion can be violated.

The tool reports the behavior is not allowed, despite the relaxation.
```
Launching Alloy...
outcome: UNSAT, outcome not permitted, breaks expectation
```

- [The dartagnan tool](https://github.com/hernanponcedeleon/Dat3M) which also supports the [PTX memory model](https://github.com/hernanponcedeleon/Dat3M/blob/master/cat/ptx-v7.5.cat) and control flow instructions
```
PTX Ticketlock-same-gpu
{
in=0; out=0;
x=0;
}
 P0@cta 0,gpu 0                    | P1@cta 0,gpu 0                   ;
 atom.relaxed.gpu.add r1, in, 1    | atom.relaxed.gpu.add r1, in, 1   ;
 LC00:                             | LC00:                            ;
 ld.acquire.gpu r2, out            | ld.acquire.gpu r2, out           ;
 beq r1,r2,LC01                    | beq r1,r2,LC01                   ;
 goto LC00                         | goto LC00                        ;
 LC01:                             | LC01:                            ;
 ld.weak r3, x                     | ld.weak r3, x                    ;
 st.weak x, 1                      | st.weak x, 2                     ;
 atom.release.gpu.add r4, out, 1   | atom.release.gpu.add r4, out, 1  ;
exists
(P0:r1 == P0:r2 /\ P1:r1 == P1:r2 /\ P0:r3 == 0 /\ P1:r3 == 0)
```

Dartagnan also reports the behavior is not allowed, despite the relaxation.
```
Condition exists (0:bv64 r1==0:bv64 r2 && 1:bv64 r1==1:bv64 r2 && 0:bv64 r3==bv64(0) && 1:bv64 r3==bv64(0))
No
```

**Comment by gonzalobg** [comment]
Thanks for the report @hernanponcedeleon ! Dartagnan looks pretty good! 

I agree that when implementing ticket locks in C++, an acquire-load for the lock count suffices; the rmw that obtains the ticket can be relaxed.

The `libcudacxx/benchmark/concurrency.cpp` was removed in: 
https://github.com/NVIDIA/cccl/commit/baaee8fb9632bf2b276915e07a42a2cd9fceb42a , so closing the bug, but we should go for a beer again !
