### ISSUE TITLE
Make Thrust matrix green

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#106]
```[tasklist]
### Tasks
- [ ] https://github.com/NVIDIA/cccl/issues/117
```

**Comment by senior-zero** [comment]
@allisonvacanti I have a WAR for CUB / llvm builds that should be present in thrust module as well. 

Symptom:
```bash
this style of line directive is a GNU extension
```

Solution:
```cmake
append_option_if_available("-Wgnu" cxx_compile_options)
append_option_if_available("-Wno-gnu-line-marker" cxx_compile_options) # WAR 3916341
```

**Comment by senior-zero** [comment]
@allisonvacanti I've applied the fix to thrust project as well, which makes everything except CTK 11.1 / llvm 9 green for thrust as well. As soon as the libcu++ issue https://github.com/NVIDIA/cccl/issues/108#issuecomment-1603460824 is addressed, and https://github.com/NVIDIA/cccl/pull/114 is merged, I think this issue can be closed.

**Comment by allisonvacanti** [comment]
Thanks @senior-zero! This is awesome.

**Comment by senior-zero** [comment]
Thrust matrix is green.
