### ISSUE TITLE
[BUG]: Disable system headers in libcu++ tests

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#1104]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

When testing CUB and Thrust, we disable system headers with `_CCCL_NO_SYSTEM_HEADER`. This leads to catching libcu++ warnings in CUB and Thrust builds. I believe we should define `_CCCL_NO_SYSTEM_HEADER` in libcu++ tests to see relevant warnings as part of the libcu++ development.  

### How to Reproduce

```bash
coder ➜ ~/cccl $ rg _CCCL_NO_SYSTEM_HEADER
libcudacxx/include/cuda/std/detail/libcxx/include/__cccl_config
64:#if !defined(_CCCL_NO_SYSTEM_HEADER)                                                     \

cub/cmake/CubBuildCompilerTargets.cmake
15:  list(APPEND cxx_compile_definitions "_CCCL_NO_SYSTEM_HEADER")

thrust/cmake/ThrustBuildCompilerTargets.cmake
30:  list(APPEND cxx_compile_definitions "_CCCL_NO_SYSTEM_HEADER")
```

### Expected behavior

libcu++ headers are not treated as system ones in libcu++ tests.

**Comment by jrhemstad** [comment]
I thought @miscco had made it so we treated libcu++ headers (but not Thrust/CUB headers) as system headers for Thrust/CUB tests?

**Comment by miscco** [comment]
We actually do disable those warning in libcu++ except for the one header `__cccl/visibility.h`, so it rather points to lack of test coverage rather than bad infrastructure settings.

In general I am opposed to disabling warnings in CI because if cub/thrust sees those warnings users will.

**Comment by miscco** [comment]
It seems like the option got lost during the preset refactor, I have added it to the default lit configuration in #1108
