### ISSUE TITLE
Define plan for Thrust/CUB kernel unification

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1189]
Below is a list of tasks in prioritized order. We should start with algorithms that already exist in CUB. This will allow delivering CUB optimizations into Thrust sooner. 

```[tasklist]
### Replace Thrust Algorithms with CUB
- [ ] #1210
- [ ] Refactor `thrust::reduce_by_key` to use `cub::DeviceReduce::ReduceByKey`
- [ ] Refactor `thrust::partition` to use `cub::DevicePartition`
- [ ] Refactor `thrust::copy_if` to use `cub::DeviceSelect`
- [ ] Refactor `thrust::unique` to use `cub::DeviceSelect::Unique`
- [ ] Refactor `thrust/extrema.h` to use `cub::DeviceReduce`
``` 

```[tasklist]
### Port Thrust Algorithms into CUB
- [ ] Port `thrust::cuda_cub::parallel_for` to CUB
- [ ] Port `thrust::merge` to CUB
- [ ] Port `thrust/thrust/system/cuda/detail/set_operations.h` to CUB
```

A few notes:
- Partition and copy doesn't have stencil overload in CUB. We might experiment with using `::Flagged` version along with a transform iterator.
- While porting `thrust::reduce_by_key` we need to decide on accumulator type.

**Comment by gevtushenko** [comment]
Updated issue description with the migration plan. Duplicated this plan in https://github.com/NVIDIA/cccl/issues/26.
