### ISSUE TITLE
[FEA]: Performance of parallel_for

### ISSUE THREAD

**Issue by ImanHosseini** [NVIDIA/cccl#1240]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

I have a stdpar kernel that achieves 0.25% compute throughput and 5.53% memory throughput. It does much better if I use alternative PSTL libraries. This is the code: https://github.com/LLNL/LULESH/blob/46c0ffcc503c300ed3ef364103499958a5c4ee16/stdpar/src/lulesh.cc#L892C11-L892C11
To compile:
```
nvc++ -w -fast -Mnouniform -Mfprelaxed -stdpar=gpu -std=c++11 lulesh-comm.cc lulesh-init.cc lulesh-util.cc lulesh-viz.cc lulesh.cc
```
And then run:
```
./a.out -s 200 -i 1
```

### Describe the solution you'd like

Better performance.

**Comment by gevtushenko** [comment]
nvbug 4432909

**Comment by gevtushenko** [comment]
Not a Thrust issue (nvbug 4432909 for more details)
