### ISSUE TITLE
[FEA]: Make Thrust types have a consistent ABI between host and device code

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1262]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

Thrust uses an inline namespace that embeds the CUDA architectures to avoid symbol collision issues. However, this causes problems where you can't pass Thrust types compiled in a host-only TU with a device TU.

### Describe the solution you'd like

Remove types like `optional`, `pair`, etc. from the inline namespace. 

```[tasklist]
### Tasks
- [ ] Finalize list of types to remove from inline namespace
```

**Comment by jrhemstad** [comment]
@robertmaynard @bdice could one or both of you help us with finalizing the list of types that RAPIDS depends on this functionality?

**Comment by miscco** [comment]
We decided that this will not be feasible rather than that we want to work with upstream to not use thrust types in API interfaces when not necessary
