### ISSUE TITLE
[DOC]: Find a way to redirect from old CUB documentation

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#1275]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

We should find a way to redirect users from old documentation https://nvlabs.github.io/cub/ to the new one https://nvidia.github.io/cccl/cub

**Comment by jrhemstad** [comment]
Duplicate with https://github.com/NVIDIA/cccl/issues/642
