### ISSUE TITLE
[DOC]: Make it more obvious that the public docs at https://nvidia.github.io/libcudacxx/ are out-dated (especially to search engines)

### ISSUE THREAD

**Issue by MatthiasKohl** [NVIDIA/cccl#1289]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

IMO, there's only a few good options for dealing with the docs at https://nvidia.github.io/libcudacxx/:
1. re-direct to https://nvidia.github.io/cccl/libcudacxx/ and potentially include the content of the old page somewhere there under "archive".
2. put a very obvious header on every single html page under https://nvidia.github.io/libcudacxx/ that it is outdated, not a single non-obvious message which only appears on the "Overview" page.

Otherwise, anyone looking for docs on APIs within libcu++ directly will most certainly miss the latest docs.
It's possible that something similar applies to cub and thrust, but I haven't confirmed this.

**Comment by jrhemstad** [comment]
Howdy and thanks for the reminder, there have been a few loose ends we hadn't tied up since our migration to the new repo and this is definitely top of that list. 

Setting up the link redirection is tracked here: https://github.com/NVIDIA/cccl/issues/642 and @wmaxey will be working on that ASAP.

**Comment by ahendriksen** [comment]
I get questions about the old docs at least once per week. Would it be possible as a temporary fix to add a large banner on top pointing to the new repo?

**Comment by ahendriksen** [comment]
I submitted a PR for the old repo to make it more clear that the old docs are deprecated and link to the new docs. 

https://github.com/NVIDIA/libcudacxx/pull/509

**Comment by jrhemstad** [comment]
Thanks to @wmaxey, any URL that pointed to the old repo will now be automatically redirected to the new docs

Try it out!  https://nvidia.github.io/libcudacxx/

**Comment by jrhemstad** [comment]
Yes!
