### ISSUE TITLE
[DOC]: Docs for dev containers should include nvidia container toolkit

### ISSUE THREAD

**Issue by ZelboK** [NVIDIA/cccl#1332]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

New

### Describe the incorrect/future/missing documentation

https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html

Someone in the discord was having troubles getting their tests for CUDA to run so I recommended them to check if their container toolkit was installed properly. They didn't install it seemingly so this solved their problem. 

I don't think external contributors would be used to using docker or devcontainers so this would be helpful to include as a prereq. It could save a lot  of time on both sides trying to diagnose the problem

### If this is a correction, please provide a link to the incorrect documentation. If this is a new documentation request, please link to where you have looked.

https://github.com/NVIDIA/cccl/blob/main/.devcontainer/README.md

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/1378
