### ISSUE TITLE
[FEA]: Implement batched memcpy benchmark / tuning

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/cccl#135]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

No

### Describe the solution you'd like

Some of the decoupled look-back based algorithms are missing benchmarks. One of those algorithms is batched memcpy. We need a benchmark / tuning for it.

We also need to extract the following parameters into algorithm tuning policy:

- warp level threshold
- block level threshold 
- buffer delay constructor 
- block delay constructor

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/136
