### ISSUE TITLE
[FEA]: CUDA vector types should implement the C++ tuple protocol

### ISSUE THREAD

**Issue by jaredhoberock** [NVIDIA/cccl#1406]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Not sure

### Is your feature request related to a problem? Please describe.

The CUDA types like `int3` defined in `<vector_types.h>` represent points. They are definitions in the global namespace and are automatically defined in every CUDA C++ program. There is no way for a CUDA C++ program to prevent their definition because these types participate in fundamental CUDA functionality like kernel launch and built-in variables. These are broadly-useful types with nice names and we are stuck with them in the global namespace.

The CUDA vector types are essentially tuples and they should behave like tuples. At the moment, they don't behave like tuples, because CUDA vector types don't implement the tuple protocol [1].

It's possible for third party libraries to implement the tuple protocol for these types themselves, but they must not do so. Firstly, because it is not their responsibility, but more importantly, because these implementations would inevitably collide when such libraries are combined.

CUDA has enhanced C++ support for these vector types in the past when constructors for these types were introduced. Making these types full-fledged tuples that can transparently participate in tuple-based libraries like CuTE and similar also makes sense.

[1] https://en.cppreference.com/w/cpp/utility/tuple/tuple-like

### Describe the solution you'd like

I believe that three things are necessary for CUDA vector types to implement the tuple protocol:

1. Provide customizations of `get`
2. Provide specializations of `std::tuple_element`
3. Provide specializations of `std::tuple_size`.

### Describe alternatives you've considered

It's possible for third party libraries to implement the solution described above, but they cannot coexist when those libraries are combined in a single program.

### Additional context

Many libraries, including the C++ Standard Library, present interfaces for _tuple-like_ types. It's inconvenient for users that the CUDA vector types do not conform to these interfaces.

**Comment by miscco** [comment]
I have opened a PR that enables full support for the various cuda vector types.

That said, there is a significant cost in code size that this carries. We will discuss this in our next team meeting
