### ISSUE TITLE
[BUG]: Fix `atomic/atomic_ref` volatile overloads.

### ISSUE THREAD

**Issue by wmaxey** [NVIDIA/cccl#1424]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Performance

### Component

libcu++

### Describe the bug

Atomics generate poor SASS due to the fact that there are no viable non-volatile overloads in the PTX and CUDA atomic layers. 

For example, in atomic_cuda.h the store dispatch will add volatile to non-volatile pointers eliminating the possibility of passing a non-volatile to a lower dispatch.
https://github.com/NVIDIA/cccl/blob/068ee47279e88cf1382f6a8edf5223fabb97ff19/libcudacxx/include/cuda/std/detail/libcxx/include/support/atomic/atomic_cuda.h#L190-L202

We need to duplicate the above code with a non-volatile pass to allow the generated PTX atomics header to be able to correctly process non-volatile atomic types when they are added to codegen.cpp.

Lastly we need to use LLVM filecheck to ensure that the PTX/SASS generated matches our expectations. This will give us longstanding proof that our `atomic_ref` implementation is as efficient as possible despite lack of compiler intrinsics for atomic operations.

### How to Reproduce

#1008 

### Expected behavior

The extraneous store should be removed.

### Reproduction link

https://godbolt.org/z/xzcjhY84W

**Comment by gonzalobg** [comment]
`volatile atomics` should include `.mmio` in their lowering to uphold what CUDA C++ promises about `volatile`.

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/1582
