### ISSUE TITLE
Identify and list features of existing extended floating point wrapper types

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1451]
@cliffburdick [said it best](https://github.com/NVIDIA/MatX/blob/b8610bc8bf1ab9ea3abfdc5ef262212b2398a0a3/include/matx/core/half.h#L44-L47): 

> CUDA does not have standardized classes/operators available on both host and device to support these operations, so we define it here.

As it happens, there appears to be a lot of projects and people who feel the same:

- [`cutlass::bfloat16_t`](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/bfloat16.h)
- [`cutlass::half_t`](https://github.com/NVIDIA/cutlass/blob/main/include/cutlass/half.h)
- [`cute::bfloat`](https://github.com/NVIDIA/cutlass/blob/a8f2c80db0564c74f4efccac71993b971dfc448b/include/cute/numeric/bfloat.hpp) (alias to `cutlass::bfloat16_t`)
- [`cute::half`](https://github.com/NVIDIA/cutlass/blob/a8f2c80db0564c74f4efccac71993b971dfc448b/include/cute/numeric/half.hpp) (alias to `cutlass::half_t`)
- [`matx::matxFp16`](https://github.com/NVIDIA/MatX/blob/main/include/matx/core/half.h)
- [`matx::matxBf16`](https://github.com/NVIDIA/cccl/blob/main/cub/test/bfloat16.h)
- [`cub::half_t`](https://github.com/NVIDIA/cccl/blob/main/cub/test/half.h)
- [`cub::bfloat16_t`](https://github.com/NVIDIA/cccl/blob/main/cub/test/bfloat16.h)
- [`c10::BFloat16`](https://github.com/pytorch/pytorch/blob/main/c10/util/BFloat16.h)
- [`c10::Half`](https://github.com/pytorch/pytorch/blob/main/c10/util/Half.h)
- [`Eigen::BFloat16`](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/arch/Default/BFloat16.h)
- [`Eigen::Half`](https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Core/arch/Default/Half.h)
- cuSPARSE made some internal wrappers too 

Things to look into:
- RAPIDS?

**Comment by weinbe2** [comment]
Kokkos has `Kokkos::Experimental::half_t` and `Kokkos::Experimental::bhalf_t`, where it'll properly wrap the data types if a given target supports it... and otherwise it's a thin wrapper around `float`.

**Comment by achirkin** [comment]
In rapidsai/raft ANN benchmarks, we don't have a wrapper; instead, we have a [uint16_t stub](https://github.com/rapidsai/raft/blob/branch-24.04/cpp/bench/ann/src/common/cuda_stub.hpp#L46) for CPU-only builds. Also across raft, the lack of `<type_traits>` support (i.e. something like `std::is_floating_point`) has been an annoying issue, which still prevents parts of raft from supporting `half`.

**Comment by jrhemstad** [comment]
> In rapidsai/raft ANN benchmarks, we don't have a wrapper; instead, we have a [uint16_t stub](https://github.com/rapidsai/raft/blob/branch-24.04/cpp/bench/ann/src/common/cuda_stub.hpp#L46) for CPU-only builds. Also across raft, the lack of `<type_traits>` support (i.e. something like `std::is_floating_point`) has been an annoying issue, which still prevents parts of raft from supporting `half`.

Thanks @achirkin, this is really helpful feedback. We've heard a lot of similar things, and so we're working on figuring out how to address all of these problems and more :)

**Comment by jrhemstad** [comment]
Awesome work @miscco. I think the only missing piece is to understand what each of these solutions does for atomic operations. Do they overload things like `atomicAdd`? Something else?

**Comment by cliffburdick** [comment]
> Awesome work @miscco. I think the only missing piece is to understand what each of these solutions does for atomic operations. Do they overload things like `atomicAdd`? Something else?
> 
> @cliffburdick was there anything you recall having to add for the matx types that you don't see reflected in the table above?

Not sure why I didn't see this. I think this is comprehensive, but one of the main issues was also having types that are compatible with their complex counterparts.
