### ISSUE TITLE
[FEA]: Update `cuda::std::invoke_result_t` to allow extended lambdas with queryable return types

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1457]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

Historically, one could not query the return type of a `__device__` lambda in host code. This is why[ we added logic to `cuda::std::invoke_result_t` to emit a compile time diagnostic](https://github.com/NVIDIA/libcudacxx/pull/284) when attempting to use it with a `__device__` lambda in host code.

However, as of CTK 12.3, there is a new feature where we _can_ query the return type of lambdas that satisfy certain conditions. This can be queried by the [new compiler trait:](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#extended-lambda-type-traits)
```
__nv_is_extended_device_lambda_with_preserved_return_type(type)
```

The current implementation of `cuda::std::invoke_result_t` will still reject lambdas where `__nv_is_extended_device_lambda_with_preserved_return_type(type)` is true: https://godbolt.org/z/PvGafeeYx

### Describe the solution you'd like

Update `cuda::std::invoke_result_t` to not emit a diagnostic when `__nv_is_extended_device_lambda_with_preserved_return_type(T)` is true.

**Comment by Revaj** [comment]
Hi, I would like to try to work with this issue :)

**Comment by miscco** [comment]
@Revaj that is awesome 🎉 

If you need any help feel free to ask here or in our [discord channel ](https://discord.com/channels/1019361803752456192/1161051667945508884)

**Comment by Revaj** [comment]
Thank you! For now I followed the guides to setup the environment and I was able to build libcudacxx.

**Comment by NNhanptnk** [comment]
Hi, I would like to work on this as well. Can I get the link the the discord channel ? @miscco

**Comment by jrhemstad** [comment]
closed by https://github.com/NVIDIA/cccl/pull/1495
