### ISSUE TITLE
[BUG]: Return Catch2 warning suppression

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#1471]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

CUB

### Describe the bug

We used to suppress a warning coming from Catch2:
https://github.com/NVIDIA/cccl/blob/71267c058bbf78933249e3040065ca27e7bba6db/cub/test/catch2_test_helper.h#L41-L51
The issue causing this warning was addressed, so we removed this suppression. There's a plan to introduce a CI config for 11.8, which will return the need for this suppression. 

Along with the suppression came a policy that `catch2_test_helper.h` has to be included after all headers. I believe this policy should evolve to the following: 1) suppress the warning only for pre-12 CTKs, 2) do not request any particular order of CUB headers.

The reason to include `catch2_test_helper.h` after CUB headers was to reveal unused variables in CUB headers. Today, we can depend on CTK 12 CI to reveal unused variables.

### How to Reproduce

Build with CTK 11.8

### Expected behavior

Successful build

**Comment by miscco** [comment]
Done in #1468
