### ISSUE TITLE
[FEA]: cuda::ceil_div

### ISSUE THREAD

**Issue by gonzalobg** [NVIDIA/cccl#1517]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

Every copy pastes this a million times, we should just include it:

```c++
__host__ __device__ constexpr size_t ceil_div(size_t a, size_t b) { return (a + b - 1)/b; }
```

### Describe the solution you'd like

-

**Comment by miscco** [comment]
I dont think this is a correct implementation, if `a+b-1` overflows then this will create bad outcomes

**Comment by gonzalobg** [comment]
This one is getting closer (see also some tests): https://gcc.godbolt.org/z/vxszn8eqE

**Comment by bernhardmgruber** [comment]
Since I have also written such a function countless times, I honestly think it should just belong into the standard. Hit me up if you want to draft a proposal.

Next on the list is `round_up_to_multiple(n, mult) -> ceil_div(n, mult) * n`.

**Comment by pauleonix** [comment]
There was [`cub::DivideAndRoundUp()`](https://github.com/NVIDIA/cccl/blob/3876dcc79eabfdd6e05c56602933bb245a8de4d5/cub/cub/util_math.cuh#L74-L90) already which is quite similar. Maybe the two should be unified?

**Comment by bernhardmgruber** [comment]
@pauleonix I already made that comment in the code you referred to :) The difference is that the CUB version accepts mixed types, and libcu++ doesn't. But this could be fixed in libcu++.
