### ISSUE TITLE
[FEA]: Disable `thrust::async` tests in CI 

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#1545]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

The `thrust::async` APIs are defunct and will be removed in a future major release. I just noticed the several of the longest running Thrust tests are `thrust::async` tests. This needlessly wastes CI resources, so we should just disable them. 
![image](https://github.com/NVIDIA/cccl/assets/15221289/7ff27a6a-6759-4032-8454-15f33b9eb61f)

### Describe the solution you'd like

Use a ctest regex to filter out `thrust::async` tests.

**Comment by alliepiper** [comment]
With #1605:

![image](https://github.com/NVIDIA/cccl/assets/58744/79b95b48-a9b8-4407-b1a4-ad770a3cea91)
