### ISSUE TITLE
[BUG]: thrust::inner_product error that does not exist before CUDA 12.4

### ISSUE THREAD

**Issue by gdwSH** [NVIDIA/cccl#1548]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

Thrust

### Describe the bug

Here is a clip of my codes:
```
        cudaMalloc((void**)&r_prev, sizeof(Real) * vec_len);
	cudaMalloc((void**)&r, sizeof(Real) * vec_len);
	cudaMalloc((void**)&p, sizeof(Real) * vec_len);
	cudaMalloc((void**)&Ap, sizeof(Real) * vec_len);
	cudaMalloc((void**)&M_inv, sizeof(Real) * vec_len * block_size);
	cudaMalloc((void**)&z_prev, sizeof(Real) * vec_len);
	cudaMalloc((void**)&z, sizeof(Real) * vec_len);
	compute_jacobi_preconditioner<Real, block_size>(A, dim, M_inv);
	if (isMemsetZero == true) cudaMemset(x, 0, sizeof(Real) * vec_len);
	spmv_cuda<Real, block_size>(A, dim, x, Ap);
	axpby_kernel<Real> << <get_blocksPerGrid(vec_len), THREADS_PER_BLOCK >> > (vec_len, r_prev, 1, b, -1, Ap);
	rTr_prev = inner_product<Real>(vec_len, r_prev, r_prev);
```
where the implementation of inner_product is as follows:
```
template <typename Real>
Real inner_product(unsigned int N, Real *a, Real *b)
{
    return thrust::inner_product(thrust::device, a, a + N, b, 0.);
}
```
The error in the terminal shows that
`CUDA error 9 [C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\include\cub/util_device.cuh, 89]: invalid configuration argument`
And the error in the prompt shows as
![image](https://github.com/NVIDIA/cccl/assets/67769141/95392803-6d92-41c8-92d1-3f5eb4758c5d)

I am sure that the memory access is legal, since no such error in previous versions of CUDA toolkits (<12.4).

### How to Reproduce

I don't even know, it's a big project with several places using thrust.

### Expected behavior

No error reported as CUDA 12.3

### Operating System

Windows 11

### nvidia-smi output

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.61                 Driver Version: 551.61         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090      WDDM  |   00000000:01:00.0  On |                  N/A |
| 36%   35C    P8             18W /  350W |     811MiB /  24576MiB |      1%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

### NVCC version

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:28:36_Pacific_Standard_Time_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0

**Comment by gdwSH** [comment]
The bug in CUDA 12.4 is that: kernel function call failed when blocksPerGrid == 0 for `any_kernel_functions<Real> << <blocksPerGrid, THREADS_PER_BLOCK >> >`

**Comment by jrhemstad** [comment]
Hey @gdwSH, thanks for reaching out.

This actually isn't an issue with Thrust. What's happening here is that launching a kernel with 0 blocks is an error, and Thrust is just picking up that error. 

To go into more detail, kernel launches with <<<>>> don't return errors directly, and instead set a global error state that can be queried with `cudaGetLastError()`. So when calling a Thrust algorithm after invoking a kernel with 0 blocks, somewhere in the Thrust code it is querying `cudaGetLastError()` and seeing the error from the kernel launch.

See https://godbolt.org/z/Kfbd7q4TE

**Comment by jrhemstad** [comment]
I'm going to close this issue. Feel free to reopen if you still have questions.
