### ISSUE TITLE
[BUG]: `aligned_size_t` constructor and conversion operator are not constexpr

### ISSUE THREAD

**Issue by fbusato** [NVIDIA/cccl#1563]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

`aligned_size_t` constructor and conversion operator are not constexpr, while the documentation reports the opposite

### How to Reproduce

see https://github.com/NVIDIA/libcudacxx/blob/4f42427dfe5fd88672c29c279637e0ccf5b47478/include/cuda/std/barrier#L28-L36

### Expected behavior

compile-time evaluation

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/1564
