### ISSUE TITLE
[BUG]:example_device_radix_sort.cu reference solution incorrectly treats `-0.f` as different from `+0.f` 

### ISSUE THREAD

**Issue by insigh** [NVIDIA/cccl#1575]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Silent Failure

### Component

CUB

### Describe the bug

```
void Initialize(
    float           *h_keys,
    int             *h_values,
    float           *h_reference_keys,
    int             *h_reference_values,
    int             num_items)
{
    Pair *h_pairs = new Pair[num_items];

    for (int i = 0; i < num_items; ++i)
    {
        RandomBits(h_keys[i]);
        RandomBits(h_values[i]);
        if (i % 5 == 0) {
            h_keys[i] = +0; 
        } else if (i % 5 == 1) {
            h_keys[i] = (double)-2 * 0; 
        } else if (i % 5 == 2) {
            h_keys[i] = -INFINITY;
        } else if (i % 5 == 3) {
            h_keys[i] = +INFINITY;
        } else {
            h_keys[i] = 1.0;
        }
        h_pairs[i].key    = h_keys[i];
        h_pairs[i].value  = h_values[i];
    }
    if (g_verbose)
    {
        printf("Input keys:\n");
        DisplayResults(h_keys, num_items);
        printf("\n\n");

        printf("Input values:\n");
        DisplayResults(h_values, num_items);
        printf("\n\n");
    }

    std::stable_sort(h_pairs, h_pairs + num_items);

    for (int i = 0; i < num_items; ++i)
    {
        h_reference_keys[i]     = h_pairs[i].key;
        h_reference_values[i]   = h_pairs[i].value;
    }

    delete[] h_pairs;
}

```
code in initialize function as shown above, then test failed;

output just like this 

> Input keys:
0, -0, -inf, inf, 1, 0, -0, -inf, inf, 1, 0, -0, -inf, inf, 1, 

Input values:
955945823, -187748513, -950634582, 227628506, -1703677129, -1052231088, 1479517882, 1143372638, -1073945326, 1138697238, 1269916527, 1764463362, -329647375, -1910978366, -1057474916, 

Reference:
-inf, -inf, -inf, -0, -0, -0, 0, 0, 0, 1, 1, 1, inf, inf, inf, 

Computed:
-inf, -inf, -inf, 0, -0, 0, -0, 0, -0, 1, 1, 1, inf, inf, inf, 

         Compare keys (selector 1): PASS
Reference:
-950634582, 1143372638, -329647375, -187748513, 1479517882, 1764463362, 955945823, -1052231088, 1269916527, -1703677129, 1138697238, -1057474916, 227628506, -1073945326, -1910978366, 

Computed:
-950634582, 1143372638, -329647375, 955945823, -187748513, -1052231088, 1479517882, 1269916527, 1764463362, -1703677129, 1138697238, -1057474916, 227628506, -1073945326, -1910978366, 

INCORRECT: [3]: 955945823 != -187748513  Compare values (selector 1): FAIL

example_device_radix_sort.cu: 217: AssertEquals(0, compare) failed.

### How to Reproduce

```
void Initialize(
    float           *h_keys,
    int             *h_values,
    float           *h_reference_keys,
    int             *h_reference_values,
    int             num_items)
{
    Pair *h_pairs = new Pair[num_items];

    for (int i = 0; i < num_items; ++i)
    {
        RandomBits(h_keys[i]);
        RandomBits(h_values[i]);
        if (i % 5 == 0) {
            h_keys[i] = +0; 
        } else if (i % 5 == 1) {
            h_keys[i] = (double)-2 * 0; 
        } else if (i % 5 == 2) {
            h_keys[i] = -INFINITY;
        } else if (i % 5 == 3) {
            h_keys[i] = +INFINITY;
        } else {
            h_keys[i] = 1.0;
        }
        h_pairs[i].key    = h_keys[i];
        h_pairs[i].value  = h_values[i];
    }
    if (g_verbose)
    {
        printf("Input keys:\n");
        DisplayResults(h_keys, num_items);
        printf("\n\n");

        printf("Input values:\n");
        DisplayResults(h_values, num_items);
        printf("\n\n");
    }

    std::stable_sort(h_pairs, h_pairs + num_items);

    for (int i = 0; i < num_items; ++i)
    {
        h_reference_keys[i]     = h_pairs[i].key;
        h_reference_values[i]   = h_pairs[i].value;
    }

    delete[] h_pairs;
}

```
code in initialize function as shown above, then test failed;

output just like this 

> Input keys:
0, -0, -inf, inf, 1, 0, -0, -inf, inf, 1, 0, -0, -inf, inf, 1, 

Input values:
955945823, -187748513, -950634582, 227628506, -1703677129, -1052231088, 1479517882, 1143372638, -1073945326, 1138697238, 1269916527, 1764463362, -329647375, -1910978366, -1057474916, 

Reference:
-inf, -inf, -inf, -0, -0, -0, 0, 0, 0, 1, 1, 1, inf, inf, inf, 

Computed:
-inf, -inf, -inf, 0, -0, 0, -0, 0, -0, 1, 1, 1, inf, inf, inf, 

         Compare keys (selector 1): PASS
Reference:
-950634582, 1143372638, -329647375, -187748513, 1479517882, 1764463362, 955945823, -1052231088, 1269916527, -1703677129, 1138697238, -1057474916, 227628506, -1073945326, -1910978366, 

Computed:
-950634582, 1143372638, -329647375, 955945823, -187748513, -1052231088, 1479517882, 1269916527, 1764463362, -1703677129, 1138697238, -1057474916, 227628506, -1073945326, -1910978366, 

INCORRECT: [3]: 955945823 != -187748513  Compare values (selector 1): FAIL

example_device_radix_sort.cu: 217: AssertEquals(0, compare) failed.

### Expected behavior

test success

### nvidia-smi output
Tue Apr  2 10:02:45 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off | 00000000:4D:00.0 Off |                    0 |
| N/A   32C    P0              63W / 400W |      4MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

### NVCC version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by insigh** [comment]
> It is expected that positive and negative zero floating point values will be treated as equivalent and is documented here: https://nvidia.github.io/cccl/cub/api/structcub_1_1DeviceRadixSort.html?highlight=device%20radix%20sort#_CPPv4N3cub15DeviceRadixSortE
> 
> > For floating-point types, -0.0 and +0.0 are considered equal and appear in the result in the same order as they appear in the input.
> 
> That said, I'm a little confused by the example provided, it seems like there are two separate issues?
> 
> I'm confused by the second set of reference/computed:
> 
> ```
> Reference:
> -950634582, 1143372638, -329647375, -187748513, 1479517882, 1764463362, 955945823, -1052231088, 1269916527, -1703677129, 1138697238, -1057474916, 227628506, -1073945326, -1910978366,
> 
> Computed:
> -950634582, 1143372638, -329647375, 955945823, -187748513, -1052231088, 1479517882, 1269916527, 1764463362, -1703677129, 1138697238, -1057474916, 227628506, -1073945326, -1910978366,
> 
> INCORRECT: [3]: 955945823 != -187748513 Compare values (selector 1): FAIL
> ```
> 
> I don't understand what's happening here because neither of those look like they are correctly sorted.

Reference treat -0.0 is not equal to +0.0, computed treat them equal;
they are both correctly sorted, but not same rule;

**Comment by Stonesjtu** [comment]
Since +0.0 is 0b0000...000, -0.0 is 1b1000...000, I don't think they are equal after twiddling.

**Comment by insigh** [comment]
> Ah, okay, the second set of values were the values in a key/value sort. That makes sense now!
> 
> What host compiler are you using? When I try `std::stable_sort` with the example input, it does not produce the same results as your reference output.
> 
> Specifically, calling `std::stable_sort` on
> 
> `{0.f, -0.f, -INFINITY, INFINITY, 1.f, 0.f, -0.f, -INFINITY, INFINITY, 1.f}`
> 
> always yields
> 
> `{-INFINITY, -INFINITY, 0.f, -0.f, 0.f, -0.f, 1.f, 1.f, INFINITY, INFINITY}`
> 
> This is because `-0.f` and `0.f` are considered equivalent and `std::stable_sort` preserves the order of equivalent elements.
> 
> https://godbolt.org/z/bsq48j6MP

the host code i use is in 
cccl/cub/device/example_device_radix_sort.cu

**Comment by jrhemstad** [comment]
Aha! I see the problem. 

The problem is with the reference solution. The `Pair::operator<` used in the `std::stable_sort` is intentionally treating `-0.f` as different from `+0.f`. 

https://github.com/NVIDIA/cccl/blob/4673d1cb666be7dc3285bac3099dd9934a4afe9a/cub/examples/device/example_device_radix_sort.cu#L65-L68

This example is very old, and so it isn't consistent with how `DeviceRadixSort` actually works today.

We'd just need to update the `Pair::operator<` to treat `-0.f` and `+0.f` as equivalent.
