### ISSUE TITLE
[FEA]: Evaluate using pre-commit for linter management

### ISSUE THREAD

**Issue by bdice** [NVIDIA/cccl#1588]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

I discussed offline with @jrhemstad about linting with pre-commit. There has been prior discussion in #456 and #455 about using clang-format in devcontainers. However, it would be nice to enable a wider range of linters for local users and CI style checks. This list might include things like trimming trailing whitespace, enforcing updates to copyright years, etc. There are many linters that integrate with pre-commit (https://pre-commit.com/). We have used this tool within RAPIDS for some time and it has eliminated many issues, such as linters having different versions on developers' local machines compared with the CI environment.

### Describe the solution you'd like

Explore adding a `.pre-commit-config.yaml` to the CCCL repository. At minimum, the configuration should include clang-format and any other style checks or linters that the project currently enforces.

### Describe alternatives you've considered

We discussed the possibility of enforcing everything with a consistent set of linters in the CCCL devcontainers but there are a few reasons this might not be ideal:

- requires a devcontainer just to run style checks (needs Docker, while pre-commit only requires Python and self-manages the hooks)
- managing more than one linter (clang-format) is difficult without a way to centralize a config. Declarative configurations like a YAML file are generally easier to work with than a long bash script that installs or runs a set of linters.
- the marginal cost of adding new linters is much smaller with pre-commit due to the widespread nature of the tool. Many linters are designed around using pre-commit as a primary mode of operation.

There is still interest in configuring format-on-save with clang-format, and pre-commit would be a complementary solution. There is a small bit of redundancy in keeping the clang-format pinning in `.pre-commit-config.yaml` in sync with the version used by the devcontainers, but this is probably a cost worth paying.

**Comment by jrhemstad** [comment]
I'm 100% sold on using `pre-commit` because coupled with https://pre-commit.ci/, this provides a complete solution to what we're looking for.

pre-commit.ci will automate enforcing _and_ applying changes via a PR comment.
