### ISSUE TITLE
[FEA]: Trim trailing whitespace and normalize newlines.

### ISSUE THREAD

**Issue by bdice** [NVIDIA/cccl#1632]
### Is this a duplicate?

- [ ] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

Following up on #455, I would like to use pre-commit to enforce that trailing whitespace is trimmed and that all files have consistent line endings.

### Describe the solution you'd like

Use hooks provided by https://github.com/pre-commit/pre-commit-hooks.

**Comment by jrhemstad** [comment]
Can we also update the root `devcontainer.json` with the following to have this happen automatically in devcontainers too? 

```
"files.eol": "\n",
"files.trimTrailingWhitespace": true
```

**Comment by bdice** [comment]
> Can we also update the root `devcontainer.json` with the following to have this happen automatically in devcontainers too?
> 
> ```
> "files.eol": "\n",
> "files.trimTrailingWhitespace": true
> ```

Good idea. I updated #1633 accordingly.
