### ISSUE TITLE
CI testing for memory errors 

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#1775]
The CUB device histogram tests had explicit checking for out-of-bounds accesses by allocating canary zones before and after temporary storage, filled with a known byte pattern before the CUB algorithm invocation and verified afterwards. These checks were removed as part of the port to Catch2 in #1695.

We could generally investigate ideas about checking for memory errors in the CI, e.g. using dedicated tools like ASAN or compute-sanitizer, or generalize the canary zone approach to larger parts of the testing infrastructure (adding it to the CUB launch wrappers).

_Originally posted by @gevtushenko in https://github.com/NVIDIA/cccl/pull/1695#discussion_r1611834780_

**Comment by alliepiper** [comment]
Closing as this will be handled by #1879. `compute-santizer`'s `--padding` arg does exactly what we want here.

**Comment by bernhardmgruber** [comment]
Awesome!
