### ISSUE TITLE
Restrict CUB device histograms to `NUM_ACTIVE_CHANNELS <= NUM_CHANNELS`

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#1792]
The `cub::DeviceHistogram::MultiHistogram***` APIs can be compiled and run with more active channels than channels in the input. E.g. having 4 active channels on a 3 channel sample. This leads to interesting results and unit test failures.

This rather seems to be by accident than a feature, so I propose disabling it via a `static_assert`.

**Comment by gevtushenko** [comment]
@bernhardmgruber I believe this is an oversight, thank you for spotting this! 

The documentation states:

> Of the ``NUM_CHANNELS`` specified, the function will only compute histograms for **the first** `NUM_ACTIVE_CHANNELS` 

Which implies to me that the number of active channels is smaller than the total number of channels. On the implementation side, active channels exceeding num channels leads to OOB access, so catching this use case as a compile-time error is preferrable.

Apart from adding a static assert, maybe we could clarify this aspect in documentation as well?
