### ISSUE TITLE
Thrust benchmark targets are confusing

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#1882]
For benchmarking CUB and Thrust, I configure (based on an internal benchmarking guide) with:
```
cmake -DCCCL_ENABLE_BENCHMARKS=YES\
      -DCMAKE_CUDA_ARCHITECTURES='90'\
      -DCMAKE_BUILD_TYPE=Release\
      -DCCCL_ENABLE_CUB=YES\
      -DCCCL_ENABLE_THRUST=YES\
      -DCCCL_ENABLE_LIBCUDACXX=NO\
      -GNinja ..
```
This gives me, among others, the following targets:
```
cub.all.benches: phony
cub.bench.adjacent_difference.subtract_left.base: phony
cub.bench.copy.memcpy.base: phony
...
thrust.all.bench: phony
thrust.bench: phony
thrust.bench.adjacent_difference.basic.base: phony
thrust.bench.adjacent_difference.custom.base: phony
thrust.bench.adjacent_difference.in_place.base: phony
thrust.bench.copy.basic.base: phony
thrust.bench.copy.if.base: phony
...
```
I can build all CUB benchmarks using the meta target `cub.all.benches`.

However, the target `thrust.all.bench` seems to build a single target executable containing a quick benchmark of several thrust algorithms. It also seems to not use nvbench and generally appears to be a bit dated, so I wonder whether it is just a legacy, given the nvbench-based thrust benchmarks.

To improve the situation I would like to at least:
* Have a meta target to build all thrust benchmarks, ideally called `thrust.all.benches` to mimic the CUB target
* Rename the `thrust.all.bench` to something that reflects its current statues.

**Comment by alliepiper** [comment]
Yeah, those are legacy benchmarks. We've kept them around for some internal QA usecases, but I think @gevtushenko may have migrated QA over to the new nvbench ones? We should remove them once they're not necessary.

**Comment by alliepiper** [comment]
Found the issue about the QA changes: #557

Looks like they can be removed now.

**Comment by alliepiper** [comment]
I've opened #1901 to remove the old target. I believe that the remaining ask here (to add the thrust.all.benches target) is the outstanding task in #557. Can we merge these issues?

**Comment by bernhardmgruber** [comment]
Thanks a lot for the big cleanup! I added commented on #557 to add the target, so this issue can be closed. Thx!
