### ISSUE TITLE
[BUG]: Compilation with thrust::async::reduce and zipped iterator fails. Trivial example

### ISSUE THREAD

**Issue by neutron-blast** [NVIDIA/cccl#1886]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

```
#include <thrust/device_vector.h>
#include <thrust/tuple.h>
#include <thrust/zip_function.h>
#include <thrust/async/reduce.h>
#include <thrust/execution_policy.h>
#include <thrust/iterator/zip_iterator.h>
#include <iostream>

// Define the tuple_sum functor
struct tuple_sum {
    __device__
    thrust::tuple<int, int> operator()(const thrust::tuple<int, int>& t1, const thrust::tuple<int, int>& t2) const {
        return thrust::make_tuple(thrust::get<0>(t1) + thrust::get<0>(t2), thrust::get<1>(t1) + thrust::get<1>(t2));
    }
};

int main() {
    // Initialize input data
    thrust::device_vector<int> d_data1{1, 2, 3, 4, 5};
    thrust::device_vector<int> d_data2{10, 20, 30, 40, 50};

    using TupleType = thrust::tuple<int, int>;
    using IteratorType = thrust::zip_iterator<thrust::tuple<thrust::device_vector<int>::iterator, thrust::device_vector<int>::iterator>>;

    // Create zip_begin and zip_end iterators
    IteratorType zip_begin = thrust::make_zip_iterator(thrust::make_tuple(d_data1.begin(), d_data2.begin()));
    IteratorType zip_end = thrust::make_zip_iterator(thrust::make_tuple(d_data2.end(), d_data2.end()));

    // Initialize the starting tuple
    TupleType init = thrust::make_tuple(0, 0);

    // Perform async reduce using zip_begin and zip_end
    auto future = thrust::async::reduce(thrust::device, zip_begin, zip_end, init, tuple_sum());

    // Get the result
    TupleType result = future.get();

    // Print the result
    std::cout << "Sum: (" << thrust::get<0>(result) << ", " << thrust::get<1>(result) << ")" << std::endl;

    return 0;
}
```

Compilation fails.

### How to Reproduce

nvcc --extended-lambda -O3 -lineinfo -Xcompiler="-march=native" thrust.cu -o thrust
/usr/local/cuda-12.5/bin/../targets/x86_64-linux/include/thrust/system/cuda/detail/async/reduce.h(204): error: no instance of function template "thrust::THRUST_200400_520_NS::distance" matches the argument list
            argument types are: (thrust::THRUST_200400_520_NS::zip_iterator<cuda::std::__4::tuple<thrust::THRUST_200400_520_NS::detail::normal_iterator<thrust::THRUST_200400_520_NS::device_ptr<int>>, thrust::THRUST_200400_520_NS::detail::normal_iterator<thrust::THRUST_200400_520_NS::device_ptr<int>>>>, std::size_t)
  noexcept(noexcept(thrust::system::cuda::detail::async_reduce_n( policy, first, distance(first, last), init, op ))) { return (thrust::system::cuda::detail::async_reduce_n( policy, first, distance(first, last), init, op )); }
                                                                                 ^
/usr/local/cuda-12.5/bin/../targets/x86_64-linux/include/thrust/detail/distance.inl(39): note #3327-D: candidate function template "thrust::THRUST_200400_520_NS::distance" failed deduction
      distance(InputIterator first, InputIterator last)
      ^
/usr/local/cuda-12.5/targets/x86_64-linux/include/cuda/std/detail/libcxx/include/__iterator/distance.h(61): note #3327-D: candidate function template "cuda::std::__4::distance" failed deduction
    distance(_InputIter __first, _InputIter __last)
    ^

### Expected behavior

Using zipped iterators with thrust::async::reduce should compile.

### Operating System

Ubuntu 22.04

### NVCC version

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Wed_Apr_17_19:19:55_PDT_2024
Cuda compilation tools, release 12.5, V12.5.40
Build cuda_12.5.r12.5/compiler.34177558_0

**Comment by bernhardmgruber** [comment]
Hi! I am rather new to the team, but I think we aliased `thrust::tuple` to `cuda::std::tuple` a while back, which we reverted in #1643 because it caused several troubles. Your miscompilation is also related, because the arguments to the unqualified call to `distance` contain both, entities from the `thrust` and `cuda::std` namespaces, so the `distance` functions from both namespaces are available and cause the ambiguity.

Thank you for finding and reporting that issue, I will post a fix shortly!
