### ISSUE TITLE
[BUG]: Policy CMP0141 is not known to CMake<3.25

### ISSUE THREAD

**Issue by phernst** [NVIDIA/cccl#1919]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

Not sure

### Describe the bug

Using CCCL with MSVC and CMake<3.25 produces the following error during CMake configuration:
```
CMake Error at cccl/CMakeLists.txt:7 (cmake_policy):
  Policy "CMP0141" is not known to this version of CMake.
```
My CMake version is 3.22, so I believe this also affects the developer build.

### How to Reproduce

1. clone the CCCL repo into some CMake project
2. add CCCL to the CMake project using `add_subdirectory`
3. try to configure the project

### Expected behavior

The configuration step of the CMake project should work without producing this error.

### Operating System

Windows 10 Pro

**Comment by jrhemstad** [comment]
@alliepiper could you take a look at this?
