### ISSUE TITLE
[BUG]: CUB 2.4.0 fails with multiple definition errors in .cpp files

### ISSUE THREAD

**Issue by valgur** [NVIDIA/cccl#1922]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

CUB

### Describe the bug

Including `cub/util_debug.cuh` (or any others that use it) from multiple .cpp files causes linking to fail with:
```
/usr/bin/ld: b.o: in function `cub::CUB_200400___CUDA_ARCH_LIST___NS::Debug(cudaError, char const*, int)':
b.cpp:(.text+0x0): multiple definition of `cub::CUB_200400___CUDA_ARCH_LIST___NS::Debug(cudaError, char const*, int)'; a.o:a.cpp:(.text+0x0): first defined here
```

This only happens with CUB 2.4.0 from CUDA 12.5.40. CUB 2.3.2 from CUDA 12.4 and older versions work fine.

I am using GCC 11 as the compiler and linker.

### How to Reproduce

1. Create files `a.cpp` and `b.cpp` with `#include <cub/util_debug.cuh>` as their contents.
2. Run
```
g++-11 -I/usr/local/cuda-12.5/targets/x86_64-linux/include -c a.cpp -o a.o
g++-11 -I/usr/local/cuda-12.5/targets/x86_64-linux/include -c b.cpp -o b.o
g++-11 a.o b.o /usr/local/cuda-12.5/targets/x86_64-linux/lib/libcudart.so -o libx.a
```

Fails with
```
/usr/bin/ld: b.o: in function `cub::CUB_200400___CUDA_ARCH_LIST___NS::Debug(cudaError, char const*, int)':
b.cpp:(.text+0x0): multiple definition of `cub::CUB_200400___CUDA_ARCH_LIST___NS::Debug(cudaError, char const*, int)'; a.o:a.cpp:(.text+0x0): first defined here
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/11/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
```

### Expected behavior

No linker errors.

### Operating System

Ubuntu Linux

**Comment by valgur** [comment]
For context, I encountered this when trying to build these source files:
- https://github.com/puzzlepaint/camera_calibration/blob/00ef4deca274377f00c3654b75b857dd20382cc2/applications/camera_calibration/src/camera_calibration/feature_detection/cuda_refinement_by_matching.h#L32
- https://github.com/puzzlepaint/camera_calibration/blob/00ef4deca274377f00c3654b75b857dd20382cc2/applications/camera_calibration/src/camera_calibration/feature_detection/cuda_refinement_by_symmetry.h#L32

**Comment by alliepiper** [comment]
I believe that has been fixed in `main` by PR https://github.com/NVIDIA/cccl/pull/1643.

The relevant change is the addition of `inline` to [this line](https://github.com/miscco/cccl/blob/a85236d934bf7fd4ea4041a0ddc81c5d053ac28c/libcudacxx/include/cuda/std/__cccl/execution_space.h#L34)

Can you try making this change locally and see if it resolves it for you?

**Comment by valgur** [comment]
Setting `_CCCL_FORCEINLINE` to `inline` fixed the issue. Thank you!

Glad to see that the fix has already been applied as well.
