### ISSUE TITLE
[BUG]: To avoid GCC to fail in preprocessing the __concept header files using "-C" option

### ISSUE THREAD

**Issue by zkhatami** [NVIDIA/cccl#1927]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

For this test:
```
#include "cuda/std/atomic"
```
GCC started failing during preprocessing with the "-C" option after this commit: 
[https://github.com/NVIDIA/cccl/commit/680c01207c8611c011ba6eed4ba30cb0c8ab2d20#diff-97033c0ba44556602cf7d7eeda4fa26ead8d8ba9ee63b55be99ae263194e124a](https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNVIDIA%2Fcccl%2Fcommit%2F680c01207c8611c011ba6eed4ba30cb0c8ab2d20%23diff-97033c0ba44556602cf7d7eeda4fa26ead8d8ba9ee63b55be99ae263194e124a&data=05%7C02%7Czkhatami%40nvidia.com%7Ca89fe25260cb467c6c4308dc9a177022%7C43083d15727340c1b7db39efd9ccc17a%7C0%7C0%7C638554672674535535%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=FDBdAcHl5XYMp70JX1056em75YIz7gnbiMK4RCUOjsI%3D&reserved=0)

This bug in GCC is triggered by the new changes in the __concept header files when using the "-C" option. 
For example, for this definition of the _Movable_ in cuda12.3 we have:
```
template<class _Tp>
_LIBCUDACXX_CONCEPT_FRAGMENT(
  _Movable_,
  requires()
  (requires(is_object_v<_Tp>),
   requires(move_constructible<_Tp>),
   requires(assignable_from<_Tp&, _Tp>),
   requires(swappable<_Tp>)));
```
, while with cuda12.4, we have:
```
_LIBCUDACXX_CONCEPT_FRAGMENT(
  _Movable_,
  requires()(// <---
    requires(is_object_v<_Tp>),
    requires(move_constructible<_Tp>),
    requires(assignable_from<_Tp&, _Tp>),
    requires(swappable<_Tp>)
  ));
```
Having the comment "//" within the code causes GCC to fail in the preprocessing phase when using "-C" option:
```
__concepts/movable.h:46:1: error: pasting "_LIBCUDACXX_CONCEPT_FRAGMENT_REQS_SELECT_PROBE_" and "/**/" does not give a valid preprocessing token
   46 | _LIBCUDACXX_CONCEPT_FRAGMENT(
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Here is the smaller reproducer that confirms this bug in GCC preprocessing when using "-C" option:
```
#define CONCAT(A, B) A ## B
/* comment */
int CONCAT(ma, /**/ in)() { }

$ g++ -E -C ec.cpp > /dev/null
ec.cpp:3:12: error: pasting "ma" and "/**/" does not give a valid preprocessing token
    3 | int CONCAT(ma, /**/ in)() { }
      |            ^~
ec.cpp:1:22: note: in definition of macro ‘CONCAT’
    1 | #define CONCAT(A, B) A ## B
      |                      
```
In the commit that CCCL has made, there is no explanation why the comment was added to those __concept header files. If the comment gets eliminated, then GCC would compile this test fine. 

### How to Reproduce

g++ -E -C ec.cpp 

### Expected behavior

To not failing in the preprocessing phase.

**Comment by dkolsen-pgi** [comment]
Replacing `//` with `/**/` won't help.  GCC chokes when a comment of any form is in the middle of a token concatenation when comments are preserved by the preprocessor (the `-C` option).
