### ISSUE TITLE
Consolidate compiler (version) detection

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#1965]
We have a couple of headers detecting what kind of compiler is in use and exposing macros accordingly:

libcu++ seems to be at root, detecting what compiler is in use in: `cuda/std/__cccl/compiler.h` and defines macros like `_CCCL_COMPILER_GCC`. However, no version macros are exposed.

Thrust has `thrust/detail/config/compiler.h`, which uses the libcu++ macros and replicates the information by defining `THRUST_HOST_COMPILER` to a set of predefined constants, e.g. `THRUST_HOST_COMPILER_GCC` (which is `2`). Thrust additionally defines compiler version macros like `THRUST_GCC_VERSION`.

CUB basically duplicates what Thrust does, exposing macros like `CUB_HOST_COMPILER` or `CUB_GCC_VERSION`.

I would really like all these macros to be consolidated into a single header inside libcu++, so I have a consistent way of asking what compiler at which version is in use.

**Comment by miscco** [comment]
the issue here is that the `THRUST_*` and `CUB_*` macros are user facing and cannot be removed as is.

I tried to remove all occurrences of those but I see that we missed some internally.

**Comment by bernhardmgruber** [comment]
I would at least like to have compiler version macros in libcu++, so I could consistenly use the libcu++ macros across Thrust, CUB and libcu++. This would also allow us to deprecate and remove the Thrust and CUB macros at some point.
