### ISSUE TITLE
[BUG]: PR #1905 breaks `nvc++ -stdpar=multicore` with older GCC versions

### ISSUE THREAD

**Issue by dkolsen-pgi** [NVIDIA/cccl#1966]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

Thrust

### Describe the bug

CCCL PR #1905 added
```
#include <cuda/cmath>
#include <cuda/std/type_traits>
```
to thrust/thrust/detail/alignment.h.  And it introduces the use of `::cuda::std::max_align_t` and `::cuda::std::alignment_of<T>` in the same file.

None of these changes are protected by an `#if` block that checks if CUDA mode is enabled.

This breaks `nvc++ -stdpar=multicore` when NVC++ is using GCC 4.x or 5.x for the standard library.  We are running into compilation errors such as:
```
nvc++ -stdpar=multicore  /proj/ta/tests/stdpar_cpp/src/all_of.cpp -o all_of.exe
".../include-stdpar/cuda/std/detail/libcxx/include/cmath", line 343: error: the global scope has no "isfinite"
  using ::isfinite;
          ^

".../include-stdpar/cuda/std/detail/libcxx/include/cmath", line 344: error: the global scope has no "isinf"
  using ::isinf;
          ^

".../include-stdpar/cuda/std/detail/libcxx/include/cmath", line 345: error: the global scope has no "isnan"
  using ::isnan;
          ^

".../include-stdpar/cuda/std/detail/libcxx/include/cmath", line 346: error: the global scope has no "signbit"
  using ::signbit;
          ^

4 errors detected in the compilation of "/proj/ta/tests/stdpar_cpp/src/all_of.cpp".
```
Because the system `<math.h>` defines those as macros rather than as functions, or doesn't define them at all.  (When CUDA mode is enabled, those functions are apparently defined as functions in one of the preincluded CUDA header files, so CCCL's `cmath` doesn't hit this problem.)

### How to Reproduce

Compile
```
#include <execution>
#include <algorithm>
int main() { }
```
with
```
nvc++ -stdpar=multicore -I<latest-CCCL-main-branch-includes> --gcc-toolchain=<gcc-4.8>
```
The NVHPC team does this a lot in our automated testing.  I can help the CCCL team set this up, or reproduce this in a different way, if necessary.

### Expected behavior

Is it expected that including `<cuda/cmath>` and using stuff from `::cuda::std` should work fine when the compiler doesn't support CUDA?  (That's an honest question.  I'm not sure what the answer is.)

If not, then `thrust/thrust/detail/alignment.h` should be fixed to not do that.

If yes, then can the CCCL team fix `<cuda/cmath>` so it works with older versions of GCC?  I realize those GCC versions are no longer supported by CCCL, so I won't be surprised if the answer is no.

**Comment by bernhardmgruber** [comment]
@dkolsen-pgi I discussed this issue during our team meeting just now and we can confirm that g++ 6 is the minimum version we support. Also, all `__host__` code of libcu++ fully supports being compiled by non-CUDA compilers like g++, so we can use libcu++ without restrictions in Thrust.

The error you are seeing was present before my PR, but my PR seemded to have surfaced it by pulling `<cuda/cmath>` into Thrust. I can roll that back but there is no guarantee someone will pull it in again by accident. I would like to avoid doing that.

> can the CCCL team fix `<cuda/cmath>` so it works with older versions of GCC? I realize those GCC versions are no longer supported by CCCL, so I won't be surprised if the answer is no.

We also would like to avoid doing that.

**Comment by dkolsen-pgi** [comment]
> The error you are seeing was present before my PR, but my PR seemed to have surfaced it by pulling `<cuda/cmath>` into Thrust.

Agreed.  The testing that I did while investigating this problem found the same results.

> I would like to avoid doing that.

> We also would like to avoid doing that.

Fair enough.  We can live with that.  Thank you for having the discussion internally and considering my requests.

This issue won't affect the NVC++ release later this month, because that will have a CCCL release, not the CCCL main branch.  In the near future NVC++ will upgrade its minimum GCC version to at least GCC 7.  I can work around the failures in the short term until we stop testing against GCC 4.8.

I am closing this issue as not implemented.
