### ISSUE TITLE
[FEA]: Investigate performance benefits of vectorized integer instructions in reductions on Hopper

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2032]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

There are specialized instructions performing vectorized int16 comparisons, for instance [__vmins2](https://docs.nvidia.com/cuda/cuda-math-api/cuda_math_api/group__CUDA__MATH__INTRINSIC__SIMD.html#_CPPv48__vmins2jj) that we are not using in device reduction. 

### Describe the solution you'd like

We should investigate if using instructions like `__vmins2` can help improve performance for small integer types on H100. Related to nvbug 4647597.

**Comment by fbusato** [comment]
realized that `__vimin3_s16x2` ([link](https://docs.nvidia.com/cuda/cuda-math-api/cuda_math_api/group__CUDA__MATH__INTRINSIC__SIMD.html#group__cuda__math__intrinsic__simd_1ga59d95f5dcc48cfb22f2eb063fc80c30e)) works even better
