### ISSUE TITLE
internal utility for pushing/popping the cuda driver's "current" device

### ISSUE THREAD

**Issue by pciolkosz** [NVIDIA/cccl#2040]
Provide a RAII utility that sets the current CUDA device/context (green context in the future?) and cleans up when the current scope ends. It should lower to the driver API using wrappers from #2042

**Comment by bernhardmgruber** [comment]
This sounds similar to `cub::SwitchDevice`. Maybe your new facility can replace/build upon it.

**Comment by pciolkosz** [comment]
Ideally, once the C++ runtime is finished you won't need it anymore 😄 
On more serious note, because we want to use driver API here, it might not be possible to unify it with the one from CUB that is using the runtime, but we can try.
