### ISSUE TITLE
Add exception type/hierarchy

### ISSUE THREAD

**Issue by pciolkosz** [NVIDIA/cccl#2044]
We should consider the exception story for the C++ Runtime and if we need some more functionality or we can just use the existing cuda_error

**Comment by bernhardmgruber** [comment]
What is "the exception story"?

**Comment by pciolkosz** [comment]
Exception types/hierarchy or maybe we can just use cuda_error and then there is nothing to do here.
We might also want to extend cuda_error with more functionality.

I should have added more context in the description, but I guess figuring out what are our option and what we need is the first task of this issue

**Comment by miscco** [comment]
For now the approach is to just use `cuda_error` whenever we interact with a cuda API.

That might change later depending on whether we have sensible sub-types for certain categories of errors.

One point that is open is how we interface with cases where a user might expect a std::exception. 

As an example a user might expect `std::bad_alloc` when an allocation fails. Currently we would always throw a `cuda_error` in that case and we might want to reconsider that

**Comment by jrhemstad** [comment]
Marking this as closed for now, we can always file a new issue if/when we need new exception types.
