### ISSUE TITLE
Support non-multiple of 4 workloads in reproducible reduction

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2112]
As we kept simplifying the reproducible reduction kernel, we removed the code path that processes incomplete tiles. This makes current code return incorrect results on inputs which size is not multiple of four (vector size). 

This issue can be closed by:
- passed test case that runs reproducible reduction of odd number of elements
- NVBench result illustrating that this chance hasn't introduced performance regressions

**Comment by SAtacker** [comment]
- [X] passed test case that runs reproducible reduction of random number of elements including both odd and even
- [X] NVBench result illustrating that this chance hasn't introduced performance regressions https://gist.github.com/SAtacker/e3410fdc01a42442645b4890c7d609a6
