### ISSUE TITLE
Benchmark and optimize `cub::DeviceFind::FindIf` against `thrust::find_if`, `thrust::count_if`.

### ISSUE THREAD

**Issue by gonidelis** [NVIDIA/cccl#2115]
Adds on top of #2114. The new `cub::DeviceFind::FindIf` algorithm needs to perform  better than `thrust::find` for most cases (with the only exception area being when predicate is satisfied rather early in the sequence). It also needs to perform better than `thrust::count_if` (with the only exception area being when predicate is satisfied first rather late in the sequence).

**Comment by jrhemstad** [comment]
Replaced by https://github.com/NVIDIA/cccl/issues/2114
