### ISSUE TITLE
[FEA]: A `cuda::uninitialized_async_buffer<T, Properties...>` that handles allocation / deallocation and other low level things for the user

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#2141]
We want this as a wrapper around a plain memory allocation, that takes care of alignment proper size calculations as well as deallocation of the memory

Importantly we also need to use this to bind the stream to the allocation so that `cuda::launch` has both available
```[tasklist]
### Tasks
```

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/1854
