### ISSUE TITLE
[BUG]: `cuda::latch` cannot be used in shared memory due to not having a default initializer

### ISSUE THREAD

**Issue by mrakgr** [NVIDIA/cccl#2208]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

Because semaphores need to be put in shared memory in order to be used, I expected that the same would apply to latches, but it seems they don't have default initializers. And of course, variables in shared memory don't accept initializers either. So what am I supposed to do?

Is it the case that I only need to give the correct scope to a latch and don't need to explicitly put its entire object into shared memory?

### How to Reproduce

Try compiling the example on Godbolt.

### Expected behavior

I expected it to compile.

### Reproduction link

https://godbolt.org/z/z9Ejd59dE

**Comment by jrhemstad** [comment]
Hey @mrakgr, thanks for reaching out! 

So this is a known sharp edge for many of the device-side synchronization primitives like `cuda::latch` that don't play well with the limitations on `__shared__` memory objects. 

The good news is that there is still a way for you to use `cuda::latch` in shared memory, it just takes a bit more work. 

The gist is that you can just allocate appropriate `__shared__` storage and then use placement new to construct the object in that storage. 

```
#include <cuda/latch>

__global__ void example_kernel() {
  using Latch = cuda::latch<cuda::thread_scope_block>;
  auto constexpr size = sizeof(Latch);
  auto constexpr alignment = alignof(Latch);
  __shared__ alignas(alignment) char storage[size];
  auto ptr = reinterpret_cast<Latch*>(storage);

  if(threadIdx.x == 0){
    new (ptr) Latch{5};
  }
  __syncthreads();
}
```

https://godbolt.org/z/69WdqE36z

**Comment by mrakgr** [comment]
Thank you for the example. I've already gone to using a regular shared var + atomics by the time I saw it, but I'll factor it out and add it to Spiral's ML library later. I'll be sure to keep it in mind.
