### ISSUE TITLE
[FEA]: Extract `cub::DeviceFor` kernels into NVRTC-compilable header

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2244]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

Python exposure of parallel algorithms relies on NVRTC compilation of CUB kernels. 
Today, `cub::DeviceFor` kernels live in dispatch header:

https://github.com/NVIDIA/cccl/blob/532ff47db0aeae4a3fd4a6e12514e89dc0550a31/cub/cub/device/dispatch/dispatch_for.cuh#L110-L157

NVRTC is unable to compile dispatch headers. This is the case mostly due to system includes. 

### Describe the solution you'd like

We have to extract `cub::DeviceFor` kernels into a standalone header. Device reduce kernels can be used as a [reference](https://github.com/NVIDIA/cccl/blob/main/cub/cub/device/dispatch/kernels/reduce.cuh). 

This issue can be closed by including a device for header into CUB NVRTC test:

https://github.com/NVIDIA/cccl/blob/532ff47db0aeae4a3fd4a6e12514e89dc0550a31/cub/test/catch2_test_nvrtc.cu#L57

**Comment by bernhardmgruber** [comment]
> NVRTC is unable to compile dispatch headers. This is the case mostly due to system includes.

Can we just get rid of system includes? Or what kind of includes are problematic? libcu++ should cover a lot and does compile with NVRTX, right?

**Comment by bernhardmgruber** [comment]
> > NVRTC is unable to compile dispatch headers. This is the case mostly due to system includes.
> 
> Can we just get rid of system includes? Or what kind of includes are problematic? libcu++ should cover a lot and does compile with NVRTX, right?

@gevtushenko ping.

**Comment by miscco** [comment]
> > > NVRTC is unable to compile dispatch headers. This is the case mostly due to system includes.
> > 
> > 
> > Can we just get rid of system includes? Or what kind of includes are problematic? libcu++ should cover a lot and does compile with NVRTX, right?
> 
> [@gevtushenko](https://github.com/gevtushenko) ping.

I believe the issue is with iterator_traits, need to work on that

**Comment by bernhardmgruber** [comment]
@miscco If it's really only that, we could save ourselves quite some refactoring time, if we prioritized getting those `iterator_traits` to work :)
