### ISSUE TITLE
[FEA]: Improve compiler macros and platform support detection

### ISSUE THREAD

**Issue by fbusato** [NVIDIA/cccl#2251]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

Add a couple of improvements for compiler macros

### Describe the solution you'd like

1. Add `__VERSION__` for `__INTEL_LLVM_COMPILER `and `__NVCOMPILER_MAJOR__/__NVCOMPILER_MINOR__` for `__NVCOMPILER`
2. Remove IBM/PowerPC/XLC support
3. ~~Provide a warning for ICC which is deprecated~~

### Additional context

see also https://github.com/NVIDIA/cccl/pull/2250,  https://github.com/NVIDIA/cccl/issues/127

**Comment by bernhardmgruber** [comment]
ICC is being addressed here: #1960

**Comment by fbusato** [comment]
Related PR for completeness https://github.com/NVIDIA/cccl/issues/2239
