### ISSUE TITLE
Implement `bit_cast` for libcu++

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#2257]
And thus spoke @miscco:

> cub has a `bit_cast` function that I really want to implement in libcu++

And I agree! Plus, we should then replace the one in CUB by the one in libcu++.

_Originally posted by @miscco in https://github.com/NVIDIA/cccl/pull/2234#discussion_r1716409747_

**Comment by fbusato** [comment]
If it can help, here is a snippet I wrote a while ago that is compatible with CUDA.
```cpp
template<typename out_t, typename in_t>
// <HOST DEVICE NODISCARD>
#if __has_builtin(__builtin_bit_cast)
constexpr
#endif
out_t bit_cast(in_t value) {
#if __has_builtin(__builtin_bit_cast)
    return __builtin_bit_cast(out_t, value);
#else
    static_assert(sizeof(out_t) == sizeof(in_t));
    static_assert(stdx::is_trivially_copyable_v<in_t>);
    static_assert(!std::is_pointer_v<in_t>);
    static_assert(!std::is_reference_v<in_t>);
    static_assert(stdx::is_trivially_copyable_v<out_t>);
    static_assert(!std::is_pointer_v<out_t>);
    static_assert(!std::is_reference_v<out_t>);
    out_t dst;
    ::memcpy(&dst, &value, sizeof(out_t));
    return dst;
#endif
}
```
please note that MSVC `constexpr` support is missing

**Comment by miscco** [comment]
> please note that MSVC `constexpr` support is missing

Its hard to see in the PR, but MSVC support is in the definition of `_LIBCUDACXX_BIT_CAST` 

The version you proposed is equivalent of the one we have, just that the static asserts are replaced by SFINAE
