### ISSUE TITLE
[FEA]: Replace `cub::accumulator_t` instances with `cuda::std::__accumulator_t`

### ISSUE THREAD

**Issue by gonidelis** [NVIDIA/cccl#2279]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

#1940 Introduces `cuda::std::__accumulator_t`. We should only use this type for accumulator types throughout all libraries and deprecate `cub::accumulator_t`. 

### Describe the solution you'd like

Replace `cub::accumulator_t` with `cuda::std::__accumulator_t`

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/1940
