### ISSUE TITLE
Introduce CI infrastructure for cuda.parallel

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#2280]
We just introduced cuda.parallel [module](https://github.com/NVIDIA/cccl/tree/main/python/cuda_parallel). This issue is about adding CI infrastructure. Testing is similar to cuda.cooperative module. In terms of dependencies, cuda.parallel module depends on libcu++, CUB, and Thrust, and CCCL/C, as well as gcc 13 compiler. 

```[tasklist]
### Tasks
- [ ] Add running cuda.parallel build/test to `test_pycuda.sh` script/jobs 
```

**Comment by gevtushenko** [comment]
Ideally, cupy will be the first adopter of the cuda.parallel package. To make cuda.parallel a dependency of cupy, we have to conver similar support matrix as cupy. @leofang can elaborate on what we should test in our CI.

**Comment by leofang** [comment]
> To make cuda.parallel a dependency of cupy, we have to conver similar support matrix as cupy. @leofang can elaborate on what we should test in our CI.

Sorry for delay. CuPy supports the Cartesian product of the following axes (cc: @kmaehashi for vis):
- Python: 3.9-3.12 (the moving window is defined as per [NEP-29](https://numpy.org/neps/nep-0029-deprecation_policy.html))
- CUDA: 11.2-11.8, 12.0-12.x (most recent two CUDA major releases that support CUDA minor version compatibility)
- OS: linux-64, linux-aarch64, win-64

For pip installation, `pip install cupy-cuda{11,12}x` is for CUDA 11.x/12.x. For conda installation, it's `conda install -c conda-forge cupy cuda-version={11,12}`, see the [CuPy Installation Guide](https://docs.cupy.dev/en/stable/install.html).
