### ISSUE TITLE
[FEA]: Improve readability of thrust tests

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#2347]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

We have a ton of tests that start with something along the lines of:

```cpp
  Vector input(5);
  Vector ref(5);
  Vector output(5);
  input[0] = 1;
  input[1] = 3;
  input[2] = -2;
  input[3] = 4;
  input[4] = -5;

   ....

  result[0] = 3;
  result[1] = 4;
  result[2] = 7;
  result[3] = 5;
  result[4] = 9;
```

This is needlessly verbose and also error prone. We should rather use initializer_list for that. Also we often later assign the `ref` output. That could also be replaced by initializer_list.

### Describe the solution you'd like

Use initializer lists to properly set and assign thrust::{host, device}_vector 

The above example would then look like:
```cpp
  Vector input = {1, 3, -2, 4, -5};
  Vector ref   = {3, 4, 7, 5, 9};
  Vector output(5);

   ....
```

In case the reference vector is reused with different data, we should simply reassign
```cpp
ref = {3, 4, 7, 5, 9};
```

**Comment by LudoDrago** [comment]
Hi, which language you plan to use ?

**Comment by miscco** [comment]
The tests still run on C++11 but I dont see any issue there
