### ISSUE TITLE
[FEA]: Update CPM to use `FetchContent_MakeAvailable`

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#2350]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

In our CI we are getting warnings of the kind:

>  CMake Warning (dev) at /usr/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
    Calling FetchContent_Populate(CCCL) is deprecated, call
    FetchContent_MakeAvailable(CCCL) instead.  Policy CMP0169 can be set to OLD
    to allow FetchContent_Populate(CCCL) to be called directly for now, but the
    ability to call it with declared details will be removed completely in a
    future version.

We should update our CPM scripts accordingly

### Describe the solution you'd like

Use the new approach

**Comment by alliepiper** [comment]
https://github.com/cpm-cmake/CPM.cmake/issues/588

This should be fixed in 0.40.1 per the above issue. #2495 updates our CPM version to 0.40.2 and should fix it.
