### ISSUE TITLE
Replace cub::DivideAndRoundUp by cuda::ceil_div

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#2375]
This requires extending `cuda::ceil_div` to accept two different data types.

> There was [`cub::DivideAndRoundUp()`](https://github.com/NVIDIA/cccl/blob/3876dcc79eabfdd6e05c56602933bb245a8de4d5/cub/cub/util_math.cuh#L74-L90) already which is quite similar. Maybe the two should be unified? 

 _Originally posted by @pauleonix in [#1517](https://github.com/NVIDIA/cccl/issues/1517#issuecomment-2331722383)_

**Comment by pauleonix** [comment]
Do we really want to have two input types? While having them forwards the decision on the type of division to [arithmetic conversion rules](https://en.cppreference.com/w/cpp/language/usual_arithmetic_conversions), the type the result is casted to is currently not decided by these rules, so I'm not sure I see the point. It might be better to let the developer explicitly cast one of the inputs in cases where they have different types.

**Comment by bernhardmgruber** [comment]
I just started refactoring and needed a different type in 4/5 cases. We often have this pattern `cub::DivideAndRoundUp(num_items, tile_size)` with `OffsetT num_items` and `int tile_size`. Those all require a cast of the second argument when we move to `cuda::ceil_div`.

**Comment by pauleonix** [comment]
Yeah, I see how it adds boilerplate (e.g. something along the lines of casting both arguments to `std::common_type_t<T1, T2>` and potentially casting the result back to `T1` to replace `DivideAndRoundUp`) to generic code. I was going to argue that explicit casting makes it clearer what is happening to the reader but I'm not convinced by that argument either since there really isn't much that can happen as the result is always representable with the type of the numerator.

I guess I just found it distracting myself when I see that template with two types (thinking about the "Why?" and the "What could go wrong?"). But some comments regarding that (ideally in documentation) should take care of those distractions for other people (or me should I forget about the answers).

**Comment by fbusato** [comment]
the choice of `ceil_div(T, T)` (with the same time) was made more for consistency with other standard c++ math api than usability

**Comment by fbusato** [comment]
my suggestion is to introduce a similar API in libcu++ for "DivideAndRoundUp" -> `ceil_div(a, b) * b` and `DivideAndRoundDown` -> `(a /  b) * b` for optimization purposes. I have the code ready if we want to go with this path

**Comment by pauleonix** [comment]
@fbusato I'm a bit confused by that suggestion. I do like the idea of also having a function that does the `* b`, but why would it be called `DivideAndRoundUp` (which in CUB currently doesn't do the `* b`) and how would these additional functions solve the initial issue? Are all instances in CUB where one needs `cub::DivideAndRoundUp` to avoid boilerplate cases where the `* b` is needed anyway?

**Comment by fbusato** [comment]
@pauleonix you are right. Sorry for the confusion. I mixed up with the discussion in [#1517](https://github.com/NVIDIA/cccl/issues/1517). I'm in favor of having two different types like in https://en.cppreference.com/w/cpp/header/functional

**Comment by pauleonix** [comment]
What in `functional` has two different types? `std::divides<T>` only has `operator()(T, T)`.  Or do you mean two different functions, `cuda::ceil_div` and another like `cub::DivideAndRoundUp`?

**Comment by fbusato** [comment]
there is also a version with `operator()(T, U)` https://en.cppreference.com/w/cpp/utility/functional/divides_void. Sorry to not directly pointed out to this version

**Comment by bernhardmgruber** [comment]
> I think all this context is reason enough to keep both

I would rather prefer unifying and upstreaming as much as possible into libcu++. The functionality of `cub::DivideAndRoundUp` is definitely generic enough to fit this case.

> there is also a version with `operator()(T, U)` https://en.cppreference.com/w/cpp/utility/functional/divides_void. Sorry to not directly pointed out to this version

This somewhat motivates me that going for a two different input type version for `ceil_div` is the right direction.
