### ISSUE TITLE
[BUG]: CCCL headers use `__host__`/`__device__` macros without defining them

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/cccl#2407]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

unsurprisingly, many cccl headers use the `__host__`/`__device__` function annotations. more surprising is the fact that they don't define those macros or explicitly include any headers that define them. that can lead to compile errors from simply including some public cccl headers

### How to Reproduce

put this in a file with the `.cpp` extension:

```c++
#include <cuda/std/type_traits>
int main() {}
```

compile with `nvcc -I path/to/libcudacxx/include -DCCCL_DISABLE_FP16_SUPPORT -c <file>.cpp` with a fresh checkout of CCCL.

result:

```
In file included from libcudacxx/include/cuda/__cccl_config:19,
                 from libcudacxx/include/cuda/std/detail/libcxx/include/__config:14,
                 from libcudacxx/include/cuda/std/detail/__config:39,
                 from libcudacxx/include/cuda/std/type_traits:14,
                 from test.cpp:1:
libcudacxx/include/cuda/std/__utility/declval.h:29:1: error: ‘__host__’ does not name a type
   29 | _LIBCUDACXX_INLINE_VISIBILITY _Tp&& __declval(int);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libcudacxx/include/cuda/std/__utility/declval.h:31:1: error: ‘__host__’ does not name a type
   31 | _LIBCUDACXX_INLINE_VISIBILITY _Tp __declval(long);
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

the `CCCL_DISABLE_FP16_SUPPORT` define is necessary with a modern (12.2+) toolkit because our `__cccl/extended_floating_point.h` header transitively includes `crt/host_device.h` for us via `cuda_fp16.h`. that doesn't happen on older toolkits so the problem reproduces there without the #define.

### Expected behavior

cccl headers should compile stand-alone, even with fp16 support disabled.

### Reproduction link

https://godbolt.org/z/ahvz3oecT

**Comment by miscco** [comment]
That is a bug in our `cuda/std/__cccl/visibility.h>` file.
We should only define those when needed
