### ISSUE TITLE
[FEA]: make `bit_cast` compatible with raw narrow precision types

### ISSUE THREAD

**Issue by fbusato** [NVIDIA/cccl#2422]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

`__half`, `__half2`, `__nv_bfloat16`, `__nv_bfloat162` are not trivially copyable and, for this reason, `bit_cast` doesn't support them. 

Looking at their implementations, they are simply defined on top of an `unsigned short`. There is no special semantic. Only the interface definition prevents a trivial copy. 

### Describe the solution you'd like

extend `bit_cast` to support narrow precision types. If not possible in `cuda::std`, I would propose another version in `cuda::`

**Comment by miscco** [comment]
That is definitely something we can and maybe should support. I believe we should reorganize our extended floating point support a bit because we are accumulating more and more special treatment for those
