### ISSUE TITLE
[FEA]: CMake `FetchContent_Populate` is deprecated

### ISSUE THREAD

**Issue by fbusato** [NVIDIA/cccl#2432]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

Recent CMake versions, e.g. 3.30, show a warning message related to the `FetchContent_Populate` call 

```
CMake Warning (dev) at cmake/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(Catch2) is deprecated, call
  FetchContent_MakeAvailable(Catch2) instead.  Policy CMP0169 can be set to
  OLD to allow FetchContent_Populate(Catch2) to be called directly for now,
  but the ability to call it with declared details will be removed completely
  in a future version.
Call Stack (most recent call first):
  cub/cmake/CPM.cmake:1004 (FetchContent_Populate)
  cub/cmake/CPM.cmake:798 (cpm_fetch_package)
  cub/test/CMakeLists.txt:22 (CPMAddPackage)
```

### Describe the solution you'd like

Suppress the warning by following the suggestion in the documentation https://cmake.org/cmake/help/latest/release/3.30.html#deprecated-and-removed-features
```
Calling FetchContent_Populate() with just the name of a dependency is now deprecated.
Projects should call FetchContent_MakeAvailable() instead.
See policy CMP0169. Calling FetchContent_Populate() with full population details rather 
than just a dependency name remains fully supported.
```

**Comment by alliepiper** [comment]
Dup of #2350
