### ISSUE TITLE
[BUG]: `cuda::std::common_type` broken

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/cccl#2464]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Silent Failure

### Component

Thrust

### Describe the bug

 `cuda::std::common_type` does not work properly with complex types in CUDA 12.6 due to an issue with nvcc. The issue is due to a pragma used in CCCL in version 2.5.0 and above, which allows CCCL 2.4.0 to work properly. However, 2.4.0 is not supported in CTK 12.6 since it ships with 2.5.0. This issue is to find a workaround until CTK is fixed that allows `common_type` to be used in CCCL. 

### How to Reproduce

Use `cuda::std::common_type` with a complex type in CTK 12.6.

### Expected behavior

`cuda::std::common_type` shows no compiler errors when used correctly.

**Comment by fbusato** [comment]
should not be related but worth mentioning https://github.com/NVIDIA/cccl/issues/2419 **[BUG]: is_common_type trait is broken when mixing rvalue references**
