### ISSUE TITLE
[FEA]: Have a less verbose pinned memory container

### ISSUE THREAD

**Issue by Kh4ster** [NVIDIA/cccl#2485]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

Currently, the least verbose way for users to have a container of pinned memory without having to write any custom code is this:

`thrust::host_vector<i_t, thrust::mr::stateless_resource_allocator<i_t, thrust::system::cuda::universal_host_pinned_memory_resource>>`

See slack discussion here: https://nvidia.slack.com/archives/CCP05T27R/p1723208979166279

### Describe the solution you'd like

I think there should be something less verbose like:

`thrust::host_vector<i_t, thrust::host_pinned>` or `thrust::pinned_host_vector<i_t>`

### Describe alternatives you've considered

Hande written allocator but users shouldn't have to do that.
Libcudf pinned host vector: https://github.com/rapidsai/cudf/pull/16206 https://github.com/rapidsai/cudf/pull/15895 which should be generally available in CCCL.

**Comment by bernhardmgruber** [comment]
Some pieces were already present in thrust, like `universal_host_pinned_memory_resource`. The unit tests were also already covering a host pinned vector.

Following existing naming conventions, the new facility will probably be called `thrust::universal_host_pinned_vector<T>`.
