### ISSUE TITLE
[DOC]: Broken link to examples in READE.md

### ISSUE THREAD

**Issue by jamesETsmith** [NVIDIA/cccl#2516]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

The link to the examples in the `README.md` is broken. I think it should point to `examples/basic`. Opening a PR for this shortly.

### If this is a correction, please provide a link to the incorrect documentation. If this is a new documentation request, please link to where you have looked.

https://github.com/NVIDIA/cccl/blob/951c822f6f97b818b911fe178f24696ce8370015/README.md?plain=1#L180

**Comment by bernhardmgruber** [comment]
The link seems to work and @miscco mentioned in #2517 that the issue was fixed in a different PR.
