### ISSUE TITLE
Python-only changes used up too much CI resource

### ISSUE THREAD

**Issue by leofang** [NVIDIA/cccl#2592]
xref: https://github.com/NVIDIA/cccl/pull/2335#issuecomment-2418394077

It's hard to locate 1 out of 380+ pipelines (for the Python one), and also it took >1 hr to run all of the CI pipelines, which was a total waste as far as #2335 was concerned. Need to only span Python pipelines and skip all C++ ones, when Python-only changes were made.

**Comment by jrhemstad** [comment]
Hmm, I suspect there's something misconfigured in the CI job dependency logic here. @alliepiper could you take a look at this? 

![Image](https://github.com/user-attachments/assets/ceeb41c9-6e54-4177-98cf-785c36368e90)
