### ISSUE TITLE
[FEA]: Provide macro for system header pragmas

### ISSUE THREAD

**Issue by DejvBayer** [NVIDIA/cccl#2600]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

Almost each file in CCCL is considered to be an implicit header. It would be better to have a single macro implementing this behaviour.
```cpp
#if defined(_CCCL_IMPLICIT_SYSTEM_HEADER_GCC)
#  pragma GCC system_header
#elif defined(_CCCL_IMPLICIT_SYSTEM_HEADER_CLANG)
#  pragma clang system_header
#elif defined(_CCCL_IMPLICIT_SYSTEM_HEADER_MSVC)
#  pragma system_header
#endif // no system header
```

### Describe the solution you'd like

Modify `libcudacxx/include/cuda/std/__cccl/system_header.h` to define compiler specific `_CCCL_SYSTEM_HEADER` macro that contains the pragma for current compiler. Then define `_CCCL_FORCE_SYSTEM_HEADER` macro for cases when the system header definition is required (maybe would be better to only use `_CCCL_SYSTEM_HEADER` instead) and `_CCCL_IMPLICIT_SYSTEM_HEADER` macro for implicit system headers.

```cpp
// libcudacxx/include/cuda/std/__cccl/system_header.h

// Enforce that cccl headers are treated as system headers
#if defined(_CCCL_COMPILER_GCC) || defined(_CCCL_COMPILER_NVHPC) || defined(_CCCL_COMPILER_ICC)
#  define _CCCL_SYSTEM_HEADER _Pragma("GCC system_header")
#elif defined(_CCCL_COMPILER_CLANG)
#  define _CCCL_SYSTEM_HEADER _Pragma("clang system_header")
#elif defined(_CCCL_COMPILER_MSVC)
#  define _CCCL_SYSTEM_HEADER __pragma(system_header)
#else // other compilers
#  define _CCCL_SYSTEM_HEADER
#endif

#define _CCCL_FORCE_SYSTEM_HEADER _CCCL_SYSTEM_HEADER // Or just use _CCCL_SYSTEM_HEADER instead

// Potentially enable that cccl headers are treated as system headers
#if !defined(_CCCL_NO_SYSTEM_HEADER)                                                     \
  && !(defined(_CCCL_COMPILER_MSVC) && defined(_LIBCUDACXX_DISABLE_PRAGMA_MSVC_WARNING)) \
  && !defined(_CCCL_COMPILER_NVRTC) && !defined(_LIBCUDACXX_DISABLE_PRAGMA_GCC_SYSTEM_HEADER)
#  define _CCCL_IMPLICIT_SYSTEM_HEADER _CCCL_SYSTEM_HEADER
#else
#  define _CCCL_IMPLICIT_SYSTEM_HEADER
#endif // Use system header
```

The typical start of the files may be then simplified to:
```
// old
// #if defined(_CCCL_IMPLICIT_SYSTEM_HEADER_GCC)
// #  pragma GCC system_header
// #elif defined(_CCCL_IMPLICIT_SYSTEM_HEADER_CLANG)
// #  pragma clang system_header
// #elif defined(_CCCL_IMPLICIT_SYSTEM_HEADER_MSVC)
// #  pragma system_header
// #endif // no system header
//
// new
_CCCL_IMPLICIT_SYSTEM_HEADER
```

**Comment by miscco** [comment]
This is not possible due to a compiler issue with nvcc that breaks compilation for certain host compilers. 

Until we deprecate the current nvcc versions (aka 2 major versions in the future) there is nothing we can do here and even then it is questionable whether we should actively break compatibility with older versions without any clear benefit.

**Comment by DejvBayer** [comment]
Oh, I did not know that. Of course it makes no sense if it breaks the compatibility backwards.
