### ISSUE TITLE
[FEA]: Im2col mode of the TMA instruction.

### ISSUE THREAD

**Issue by hcube123** [NVIDIA/cccl#2617]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

The file `cp_async_bulk_tensor.h` only  provides` cp.async.bulk.tensor` instructions for `tile` mode, not `im2col`.
Some of the comments in that file don't match either.

### Describe the solution you'd like

Complement ` im2col` model implementation in the ` libcudacxx\include\cuda\__ptx\instructions` directory.

### Describe alternatives you've considered

Can you give a demo of the im2col instruction like the _CUDA C++ Programming Guide_

**Comment by miscco** [comment]
@hcube123 Thanks for suggesting that.

We generally aspire to provide wrappers for all ptx functionalities. The issue is just prioritization and having enough manpower to work on this.
