### ISSUE TITLE
[BUG]: confusing defns of `_CCCL_CUDACC_BELOW_XX_X` pessimizing builds

### ISSUE THREAD

**Issue by ericniebler** [NVIDIA/cccl#2686]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Silent Failure

### Component

libcu++

### Describe the bug

i recently discovered that macros like `_CCCL_CUDACC_BELOW_12_2` get defined if there is no CUDA compiler; that is, if we're compiling as straight-up C++.

```c++
#if !defined(_CCCL_CUDA_COMPILER) || (defined(_CCCL_CUDACC) && _CCCL_CUDACC_VER < 1202000)
#  define _CCCL_CUDACC_BELOW_12_2
#endif // defined(_CCCL_CUDACC) && _CCCL_CUDACC_VER < 1203000
```

many of the uses of these macros i've seen in cccl seem to suggest the author thought that `_CCCL_CUDACC_BELOW_12_2` would only be defined if there was indeed a cuda compiler _and_ it was below 12.2, which is not the case.

For example, consider this from `<cuda/std/__cccl/attributes.h>`:

```c++
// NVCC below 11.3 does not support nodiscard on friend operators
// It always fails with clang
#if defined(_CCCL_CUDACC_BELOW_11_3) || defined(_CCCL_COMPILER_CLANG)
#  define _CCCL_NODISCARD_FRIEND friend
#else // ^^^ _CCCL_CUDACC_BELOW_11_3 ^^^ / vvv !_CCCL_CUDACC_BELOW_11_3 vvv
#  define _CCCL_NODISCARD_FRIEND _CCCL_NODISCARD friend
#endif // !_CCCL_CUDACC_BELOW_11_3 && !_CCCL_COMPILER_CLANG
```

clearly the author only intended to avoid `[[nodiscard]]` if the compiler is nvcc pre-11.3 or if the compiler is clang. instead, when compiling as pure C++ (no CUDA compiler) we _always_ avoid putting `[[nodiscard]]` on friend functions, regardless of the compiler.

for example, when i preprocess the following file with gcc (`g++ -I cccl/libcudacxx/include -E test.cpp`)...

```c++
#include <cuda/__cccl_config>

struct S
{
  _CCCL_NODISCARD_FRIEND int fn(S)
  {
    return 0;
  }
};
```

i get:

```c++
struct S
{
  friend int fn(S)
  {
    return 0;
  }
};
```

no `[[nodiscard]]` attribute, despite the fact that gcc has no troubles with `[[nodiscard]]` on friends.

i'm not 100% sure what the right fix here is. i'd like to see `_CCCL_CUDACC_BELOW_XX_X` undefined if there is no CUDA compiler, but someone would need to go through all the uses of these macros and figure out what the author's intention was.

### How to Reproduce

see above

### Expected behavior

n/a

**Comment by ericniebler** [comment]
@miscco assigning this to you since you were the one who made this change in [27253d72]. i'm curious what motivated this change.

**Comment by miscco** [comment]
I believe that was because of clang-cuda not having the proper defines in place, which has been subsequently fixed
