### ISSUE TITLE
[BUG]: pow_complex_complex.pass.cpp fails in unoptimized builds

### ISSUE THREAD

**Issue by Artem-B** [NVIDIA/cccl#2741]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

libcu++

### Describe the bug

The test uses exact FP comparison for the operation results, and it fails in unoptimized builds where exp/log operations are not optimized away, and we accumulate some errors.

### How to Reproduce

Compile the test w/o optimizations. Run. Observe it failing on `double` tests on a GPU (tested on sm_60, 80, 89)

On GPU:
```
third_party/gpus/cccl/v2_6_0/libcudacxx/test/libcudacxx/std/numerics/complex.number/complex.transcendentals/pow_complex_complex.pass.cpp:62: void test_edges() [T = double]: block: [0,0,0], thread: [0,0,0] Assertion `imag(r) == imag(z)` failed.
CUDA devices found: 1
Device 0: "NVIDIA A100-SXM4-40GB", Selected, SM80, 42298834944 [bytes]
CUDA ERROR, line 110: cudaErrorAssert: device-side assert triggered
```

### Expected behavior

Tests should not use exact FP comparison unless there's a very good reason to expect precise result.

**Comment by miscco** [comment]
I am not sure about it. There are actually a ton of requirements that certain identities hold. I can check that but we do know that our implementation is not fully conformant

**Comment by Artem-B** [comment]
Full list of the failed test cases: https://gist.github.com/Artem-B/19807d5e4f2e3efb0e3d6319ebed1809

It appears that the issue only affects `double` tests on a GPU.
