### ISSUE TITLE
[DOC]: Mention `skip-tests` convention for commits that should not trigger CI in ci-overview

### ISSUE THREAD

**Issue by wence-** [NVIDIA/cccl#277]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

As seen in discussion in #274, if a PR only updates the docs, it is recommended to add `[skip-tests]` to the commit message to avoid running CI on a change that doesn't need it (modulo perhaps building the docs to check nothing is broken?). However, this is not a discoverable feature for a casual contributor (it's only by reading the dispatch workflow that you can determine how this works).

Aside, one might be able to take advantage of either [workflow-level path skipping](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), or else a third-party workflow to [job level path filter](https://github.com/dorny/paths-filter) to automate skipping of expensive CI for docs only changes.

**Comment by jrhemstad** [comment]
Closed by https://github.com/NVIDIA/cccl/pull/500
