### ISSUE TITLE
[FEA]: Define compiler id macros to true value

### ISSUE THREAD

**Issue by davebayer** [NVIDIA/cccl#2783]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

CCCL supports various host compilers. Currently, the host compiler dependent code is implemented as:
```cpp
#if defined(_CCCL_COMPILER_MYCOMPILER)
// ...
#endif // defined(_CCCL_COMPILER_MYCOMPILER)
```
This is a simple case, however, if the code is dependent on multiple host compilers, the conditions start to get very verbose.

### Describe the solution you'd like

We could take an advantage of the fact that when preprocessor `#if` statement is evaluated, unknown identifiers are replaced with `0`. If define compiler id macros to `1`, the `defined(_CCCL_COMPILER_MYCOMPILER)` can be replaced with simple `_CCCL_COMPILER_MYCOMPILER`. It makes the code more readable.

**Comment by fbusato** [comment]
I proposed the same change in https://github.com/NVIDIA/cccl/pull/2503. Unfortunately, it was not accepted. @miscco

**Comment by davebayer** [comment]
Oh I see, I did not dive that deep into the issues.. Never mind, thanks for the reply.

**Comment by miscco** [comment]
I believe there were different issues at play.

1. We do not want these macros to be user visible
2. There is an immense amount of code that needs to change all at once.
3. There is some benefit but its mostly cosmetic. Outside of the configuration headers there is rarely a duplicated clause

**Comment by fbusato** [comment]
I perfectly agree on the first two points. Macros are more problematic to maintain, and we don't expect to change all of them in a single step. 
IMO, it is not only a cosmetic change. I was tempted to wrongly write `#if _CCCL_COMPILER_XYZ` many times.

@davebayer, we discussed it offline with @miscco and @bernhardmgruber.  We are fine with this PR
