### ISSUE TITLE
[FEA]: Provide `std::dims`

### ISSUE THREAD

**Issue by fbusato** [NVIDIA/cccl#2810]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

`std::dims` simplifies the definition of `mdspan` extents

### Describe the solution you'd like

Provide `std::dims` (C++26) and backport to C++14/17

**Comment by bernhardmgruber** [comment]
Paper: https://wg21.link/p2389r2
