### ISSUE TITLE
Ambiguous cuda:: namespace issue

### ISSUE THREAD

**Issue by vikasnkumar** [NVIDIA/cccl#2939]
[Line 422 ](https://github.com/NVIDIA/cccl/blob/83d180f487ac85c3985d39835d665ae676ba49b0/cub/cub/device/dispatch/dispatch_histogram.cuh#L422) should be `::cuda::proclaim...` so that the ambiguous compiler errors go away.

**Comment by bernhardmgruber** [comment]
Thx for catching that! Feel free to propose a PR directly next time ;)

**Comment by vikasnkumar** [comment]
> Thx for catching that! Feel free to propose a PR directly next time ;)

Will do. if you still want me to do a PR i can do one, if you prefer it that way.
