### ISSUE TITLE
Gather inventory of CuPy's CCCL usage

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#2959]
We'd like a list of:
- Every Thrust/CUB function used in CuPy today
- Thrust/CUB functions CuPy would *like* to be using but cannot

**Comment by shwina** [comment]
This is just an initial analysis. CUB and Thrust usage in CuPy can be found in [cupy_cub.cu](https://github.com/cupy/cupy/blob/main/cupy/cuda/cupy_cub.cu) and [cupy_thrust.cu](https://github.com/cupy/cupy/blob/main/cupy/cuda/cupy_cub.cu) respectively. 

## cub

* `DeviceReduce` 
* `DeviceSegmentedReduce` 
* `DeviceScan`
* `DeviceSpmv`  
* `DeviceHistogram` 

## thrust

* `stable_sort` 
* `stable_sort_by_key` 

For sorting a muilti-dimensional array along a specified axis (dimension), there’s a specialized algorithm which additionally uses:

* `sequence` 
* `transform` 
* `thrust::device_pointer_cast` 
* `thrust::device_ptr` 
* `thrust::tuple`, `thrust::get` 
* `thrust::make_counting_iterator` 
* `thrust::make_constant_iterator` 
* `thrust::divides` 

## cub “patching”

In addition, within `cupy_cub.cu` there’s some code that specializes/supplements cub: 

* Specializations like `numeric_limits<thrust::complex<float>>>` to support complex numbers
* Specializing operators like `Max()`, `Min()` etc., for floats to handle NaNs in a way that matches NumPy semantics. 

I’m not entirely sure how CuPy can switch to using `cuda.parallel` with the above specializations. Something to keep in mind.

**Comment by leofang** [comment]
> This is just an initial analysis. CUB and Thrust usage in CuPy can be found in [cupy_cub.cu](https://github.com/cupy/cupy/blob/main/cupy/cuda/cupy_cub.cu) and [cupy_thrust.cu](https://github.com/cupy/cupy/blob/main/cupy/cuda/cupy_thrust.cu) respectively.

The list looks fine to me.

**Comment by leofang** [comment]
I suggested during the meeting that we deprioritize `DeviceHistogram` because of several issues, e.g. https://github.com/NVIDIA/cccl/issues/912
