### ISSUE TITLE
[BUG]: `THRUST_DEVICE_SYSTEM` is missing from ccmake

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#2963]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

Thrust

### Describe the bug

Previously, configuring CCCL with cmake would expose the cache variable `THRUST_DEVICE_SYSTEM` in the cmake tui (`ccmake`). The variable seems to have disappeared.

This is unfortunate, since it makes switching backends inside a build directory unnecessarily harder.

### How to Reproduce

Run from a CCCL git clone:
```bash
mkdir build_dir
cd build_dir
cmake ..
ccmake ..
```
Shows the following Thrust-related variables:
```
 THRUST_CPP_DIALECT               17
 THRUST_DISPATCH_TYPE             Dynamic
 THRUST_ENABLE_EXAMPLES           ON
 THRUST_ENABLE_EXAMPLE_FILECHEC   OFF
 THRUST_ENABLE_HEADER_TESTING     ON
 THRUST_ENABLE_MULTICONFIG        OFF
 THRUST_ENABLE_RDC_TESTS          ON
 THRUST_ENABLE_TESTING            ON
 THRUST_FORCE_RDC                 OFF
 Thrust_ENABLE_INSTALL_RULES      ON
```

### Expected behavior

The variable `THRUST_DEVICE_SYSTEM` should be displayed as it used to be.

**Comment by alliepiper** [comment]
That variable is hidden when `THRUST_ENABLE_MULTICONFIG=ON`, since it'd otherwise conflict with the multiconfig state.

**Comment by alliepiper** [comment]
It's worth pointing out that the singleconfig stuff isn't really used or tested anymore and is likely to have more issues.

Rather than changing the system in a build directory, why not just use the `all-dev` preset and just build the targets from the host/device/dialect triple you're interested it?

**Comment by bernhardmgruber** [comment]
> It's worth pointing out that the singleconfig stuff isn't really used or tested anymore and is likely to have more issues.

I could be convinced that we should drop the singleconfig stuff in the interest of a simpler build system.

> Rather than changing the system in a build directory, why not just use the `all-dev` preset and just build the targets from the host/device/dialect triple you're interested it?

That's a valid workflow for developing. However, when I test, profile, debug, hunt bugs, etc. I tend to try through different configurations while repeating the same commands over and over again. I find it easier if the target name does not change every time I change the configuration.

But again, if the benefit of dropping singleconfig mode is lage, I can cope.
