### ISSUE TITLE
Inventory existing CUDA samples

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#2974]
Similar to the exercise we did for mapping existing CUDA runtime APIs to cudax:: functionality, we should do the same thing for existing CUDA samples.

**Comment by pciolkosz** [comment]
Done in [https://docs.google.com/spreadsheets/d/1ril39-2uh9IYi6qfQwNZ5TzFD89G3vnLrxj2v_x9umM/edit?gid=1755585281#gid=1755585281](https://docs.google.com/spreadsheets/d/1ril39-2uh9IYi6qfQwNZ5TzFD89G3vnLrxj2v_x9umM/edit?gid=1755585281#gid=1755585281)
