### ISSUE TITLE
[FEA]: Enable assertions by default in CMake Debug builds

### ISSUE THREAD

**Issue by bernhardmgruber** [NVIDIA/cccl#2975]
I got asked by someone what the state of the art way to enable assertions, e.g. to trigger on OOB access on a `cuda::std::span` is for CCCL. I replied that we cannot do anything for plain nvcc (yet), because we don't know whether the users intends to have a debug or release build. But if CCCL is consumed via CMake, we would look at the `CMAKE_BUILD_TYPE` and define `CCCL_ENABLE_ASSERTIONS`. Or are we?

I did not find where CMake would define `CCCL_ENABLE_ASSERTIONS` when any of the CCCL libraries is imported, so I conclude that we don't enable assertions anywhere. I think we should enable them for CMake Debug builds.

**Comment by jrhemstad** [comment]
> I think we should enable them for CMake Debug builds.

Agreed.

**Comment by bernhardmgruber** [comment]
@Kh4ster would love to have soon
