### ISSUE TITLE
[DOC]:  Typo in document of binary_search.h

### ISSUE THREAD

**Issue by hzhangxyz** [NVIDIA/cccl#2980]
### Is this a duplicate?

- [ ] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Is this for new documentation, or an update to existing docs?

Update

### Describe the incorrect/future/missing documentation

In https://nvidia.github.io/cccl/thrust/api/function_group__binary__search_1ga1ccd67cb0e378d441f38cea77ca3dfd5.html , several `input.end()` is written as `input.end` by mistake.

For example:

- https://github.com/NVIDIA/cccl/blob/a5d33e070708f65234b353baed0df380bad4b367/thrust/thrust/binary_search.h#L759
- https://github.com/NVIDIA/cccl/blob/a5d33e070708f65234b353baed0df380bad4b367/thrust/thrust/binary_search.h#L760

You could search `end)` in this file for all tyro.

### If this is a correction, please provide a link to the incorrect documentation. If this is a new documentation request, please link to where you have looked.

https://nvidia.github.io/cccl/thrust/api/function_group__binary__search_1ga1ccd67cb0e378d441f38cea77ca3dfd5.html

**Comment by bernhardmgruber** [comment]
Hi! Great catch! Feel free to submit a PR to fix those. Otherwise, I can create one later.
