### ISSUE TITLE
[FEA]: Add out of bound assertion to cuda::std::span on operator()

### ISSUE THREAD

**Issue by Kh4ster** [NVIDIA/cccl#3045]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

cuda::std::mdspan doesn't trigger, in debug, an assertion when an out of bound access is performed via operator(), contrary to cuda::std::span (with its operator[]).

### Describe the solution you'd like

cuda::std::mdspan should trigger an assertion, in debug, in both host and device just like cuda::std::span.

We will also have to update the following: https://github.com/NVIDIA/cccl/blob/main/docs/libcudacxx/standard_api/container_library/mdspan.rst

### Describe alternatives you've considered

Using cuda::std::span but we want to promote cuda::std::mdspan as a safe multi-dimensional accessor

### Additional context

Came in a discussion with @bernhardmgruber on slack. The goal is for it to be used in the "The Modern CUDA Developer’s Toolbox" future blogpost.

**Comment by bernhardmgruber** [comment]
@fbusato since you are working on mdspan at the moment, maybe you have time to add an assertion to `operator()` and `operator[]`.

**Comment by bernhardmgruber** [comment]
@fbusato it seems @miscco was faster.
