### ISSUE TITLE
[Internal Cleanup] Resolve "ATTENTION: NOT op_caller here!" vs "ATTENTION: op_caller here" asymmetry in Transform Iterator implementation.

### ISSUE THREAD

**Issue by rwgk** [NVIDIA/cccl#3064]
I will update this issue description with source code references after PR #2788 is merged.

Current best guess: Eliminating `@overload` will sidestep the issue.
 
Relevant links provided by @gmarkall (in a meeting on 2024-11-27):
* https://www.nvidia.com/en-us/on-demand/session/gtcspring22-s41056/ 
* https://github.com/gmarkall/life-of-a-numba-kernel
* https://github.com/gmarkall/numba-accelerated-udfs
* https://github.com/NVIDIA/numba-cuda/blob/main/numba_cuda/numba/cuda/intrinsics.py#L28

**Comment by shwina** [comment]
> Current best guess: Eliminating @overload will sidestep the issue.

In general, using the extension API to define the typing and lowering for iterator types and their advance/deref functions will simplify things greatly. See for example https://github.com/gmarkall/numba-accelerated-udfs/blob/main/filigree/numba_extension.py.
