### ISSUE TITLE
[cuda-python]: Implement compiler caches

### ISSUE THREAD

**Issue by rwgk** [NVIDIA/cccl#3193]
Primary issue: https://github.com/NVIDIA/cuda-python/issues/176

Creating this issue for easy CCCL sprint planning.

The work on cuda-python is meant to set the stage for using `cuda.core.cache` (or similar ) from `cuda.parallel`.

**Comment by leofang** [comment]
@jollylili when you get a chance, could you kindly check it out and see if there's a way we can make one task appearing in multiple project boards (in this case, CCCL & CUDA Python), instead of assignees having to duplicate the tasks in multiple places? It would only add to confusion.

**Comment by jollylili** [comment]
@leofang it can be done by selecting multiple project boards on the "Projects" panel on the right hand side of this window. I saw this issue already got pulled over to CCCL and CUDA Python.

**Comment by rwgk** [comment]
@gevtushenko @leofang I will close this now, because in our meeting that ended just now we decided that the caching for cuda.parallel will not use cuda.core.

For completeness / easy future reference: In the same meeting #2590 was reassigned to @shwina.
