### ISSUE TITLE
[FEA]: CUDA Graph Capture support for CUB routines

### ISSUE THREAD

**Issue by fbusato** [NVIDIA/cccl#321]
### Is this a duplicate?

- [ ] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

Multiple CUB routines fail if executed in a CUDA graph

### Describe the solution you'd like

Add test cases in the unit test to ensure that all routines support CUDA graph capture

**Comment by senior-zero** [comment]
Hello @fbusato! 

> Multiple CUB routines fail if executed in a CUDA graph

I can verify that graph capture is not tested nor documented. Besides that, not all CUB algorithms are  graph capture friendly. One algorithm that definitely doesn't support graph capture is `DeviceSegmentedSort`. Could you share what are the remaining algorithms that do not support graph capture? 

> Add test cases in the unit test to ensure that all routines support CUDA graph capture

I'm not sure if we'd want to provide a library-wide guarantee. Do you think the guarantee could be given on a per-algorithm basis? If so, could you provide a list of algorithms that are crucial for your use case?

**Comment by fbusato** [comment]
Hi @senior-zero , I don't want to focus this request on a specific algorithm or subset of algorithms.  My suggestion is to ensure/verify graph capture for as many algorithms as possible and document where it works and where it doesn't. In the end, my guess is that it is only a few lines of code to add to test this feature.
