### ISSUE TITLE
[FEA]: TBB in devcontainers

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cccl#323]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Infrastructure

### Is your feature request related to a problem? Please describe.

We need to be able to test Thrust's TBB backend in both CI and local devcontainers.

### Describe the solution you'd like

The devcontainers should provide the tbb libraries in a discoverable location.

**Comment by jrhemstad** [comment]
I've been meaning to get around to this. And for openmp.

We would need to add these as features to https://github.com/rapidsai/devcontainers and then we could add them to our containers.

cc @trxcllnt

**Comment by trxcllnt** [comment]
@jrhemstad should we add these to the images with oneapi, or as a separate feature?

**Comment by jrhemstad** [comment]
This was done by https://github.com/rapidsai/devcontainers/pull/113
