### ISSUE TITLE
[BUG]: catch2 binary runs into frequent time outs

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#356]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

CUB

### Describe the bug

Our catch2 test binary has grown over time.

We are now running into timeouts during CI which frequently require manual intervention / rerunning of jobs.

We should consider splitting the catch2 binary into one per test to lessen the burden on the test infrastructure. There is a build configuration for that, so it should not be too invasive

### How to Reproduce

Look at Ci with a red x

### Expected behavior

Our tests should not run into timeouts

**Comment by jrhemstad** [comment]
I haven't seen the timeouts. Can you link to a CI run where that is happening?

**Comment by miscco** [comment]
Nope, it seems the history of previous runs is not preserved (I usually just go on rerun failed)

**Comment by jrhemstad** [comment]
The history is preserved. Can you link me to a job that you reran?

**Comment by miscco** [comment]
I think it was one of those https://github.com/NVIDIA/cccl/actions/runs/5901530254/job/16008369320

**Comment by miscco** [comment]
Ah I got it https://github.com/NVIDIA/cccl/actions/runs/5888238667/attempts/1

**Comment by allisonvacanti** [comment]
We can hardcode a higher timeout in cmake. Is this still an issue?
