### ISSUE TITLE
[BUG]: LIBCUDACXX_DEBUG_ASSERT takes string argument (and none currently provided in many cases)

### ISSUE THREAD

**Issue by ahendriksen** [NVIDIA/cccl#386]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

libcu++

### Describe the bug

Many instances of 
```
#if (_LIBCUDACXX_DEBUG_LEVEL >= 2)
        _LIBCUDACXX_DEBUG_ASSERT(__count >= 0);
#endif

```
When the debug_level actually exceeds 2, the code fails to compile, because `_LIBCUDACXX_DEBUG_ASSERT` takes two arguments.

### How to Reproduce

Option A: Remove one of the `#if (_LIBCUDACXX_DEBUG_LEVEL >= 2)` guards and try to compile.
Option B: Compile with `-D__LIBCUDACXX_DEBUG_LEVEL=2`.

### Expected behavior

The library should continue to compile with higher debug levels.

### Reproduction link

https://cuda.godbolt.org/z/5d44zKvWK

**Comment by miscco** [comment]
This is indeed a bug, asserts should always take a string explaining the issue at hand.

I have pushed a fix to your PR

**Comment by ahendriksen** [comment]
Okay. I thought the issue was way more widespread than it was in reality. The asserts in annotated_ptr and elsewhere do include a string argument.. Should have fixed this myself in the barrier PR ^^
