### ISSUE TITLE
[FEA]: Provide label to track sm_90 feature exposure

### ISSUE THREAD

**Issue by gonzalobg** [NVIDIA/cccl#392]
### Is this a duplicate?

- [x] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

Tasks for sm_90 feature exposure are not easy to discover. Provide a label for feature exposure for particular sm_xx , to identify the features for the epic of each sm_xx.

### Describe the solution you'd like

See above.

**Comment by jrhemstad** [comment]
We generally aren't using labels this way. Instead, we have overarching theme/epic issues that track other issues via tasklists.

For example, here's the tracking issue for Hopper CUDA C++ Feature Exposure: https://github.com/NVIDIA/cccl/issues/35
