### ISSUE TITLE
[FEA]: Add support for tests that compile, but fail at runtime

### ISSUE THREAD

**Issue by ahendriksen** [NVIDIA/cccl#417]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

In review, an additional test was requested that should compile successfully, but fails at runtime. 

> - fail tests checking that the APIs fail on non-supported state spaces

_Originally posted by @gonzalobg in https://github.com/NVIDIA/cccl/pull/358#pullrequestreview-1615182964_
            

### Describe the solution you'd like

Add `.runfail.cpp` test type that is tested to compile correctly and to fail at runtime.

### Describe alternatives you've considered

Naively, ff you want to test for success, you can also test for failure. There is one case where this is not true though and that is when we want the code to correctly assert when preconditions are not met.

**Comment by jrhemstad** [comment]
Could we use `XFAIL: *` in lit for this? 

https://llvm.org/docs/TestingGuide.html#constraining-test-execution

**Comment by jrhemstad** [comment]
Ah, I suppose the difference is that you want to assert that it compiles successfully and fails during execution. @wmaxey or @miscco would need to confirm, but I think `XFAIL` will "succeed" even if it fails to compile.

**Comment by ahendriksen** [comment]
Exactly.
________________________________
