### ISSUE TITLE
[BUG]: "bash: nvcc: command not found" On Jetson Nano (4GB)

### ISSUE THREAD

**Issue by mericgeren** [NVIDIA/cccl#446]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Something else

### Component

Not sure

### Describe the bug

Hello,

I have installed Jetpack 4.6.4 from quick start guide with micro sd on a Jetson Nano recently. After the installation i had 3 cuda folders inside `usr/local` named "cuda", "cuda-10" and "cuda-10.2" and nvcc was working. Then, i tried to install and build OpenCV with CUDA support following these steps specified [here](https://qengineering.eu/install-opencv-on-jetson-nano.html) under " Installation script." section. The build have failed. Then, when i checked "usr/local" and saw there is only "cuda-10.2" . After that, i tried `nvcc --version` and saw:
 
>bash: nvcc: command not found 

After that, created a link with `sudo ln -sfT /usr/local/cuda-10.2/ /usr/local/cuda` command. Then, checked if it works with `ls -l /usr/local/cuda` command and got this on my terminal: 

>lrwxrwxrwx 1 root root 21 Sep 13 11:46 /usr/local/cuda -> /usr/local/cuda-10.2/ 

Then, checked my .bashrc file and there were these lines at the end of .bashrc: 

```

 export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
 export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

```

Then tried again the command: `nvcc --version` and got `bash: nvcc: command not found` on my terminal again. Later on, i checked with `jtop` and saw these lines at the "info" section:

```
Libraries

cuDNN: 8.2.1.32

TensorRT: 8.2.1.8

CUDA: MISSING

Vulkan: 1.2.70

VPI: 1.2.3

OpenCV: 4.1.1 with CUDA: NO
```

### How to Reproduce

1. Flash JetPack to Jetson Nano with micro sd method.
2. Be sure that these two lines are present at the end of .bashrc:

```

export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}

```

3. Follow steps specified [here](https://qengineering.eu/install-opencv-on-jetson-nano.html) under "Installation script."
4. See that line: "-- Configuring incomplete, errors occurred!"
5. Check "/usr/local" and see that there is only "cuda-10.2" as cuda folder.
6. Enter the command `nvcc --version` and see "bash: nvcc: command not found
"
7. Check status of CUDA with "jtop" and see that CUDA is missing.

### Expected behavior

Seeing version of nvcc when entering the command `nvcc --version` and seeing CUDA version when checking with "jtop".

### Operating System

L4T 32.7.4 (Based on Linux 18.04)

### nvidia-smi output

Not available. Since, i am using Jetson Nano.

### NVCC version

The issue is not being able to check it.

**Comment by miscco** [comment]
Hi @mericgeren,

I fail to see how this is a cccl issue? We are not responsible for OpenCV installation documentation.

Furthermore, I am afraid that the installed 10.2 version is not supported, as we require at least 11.0.

Anyway you can always download the cuda toolkit from here https://developer.nvidia.com/cuda-downloads

**Comment by mericgeren** [comment]
Hi @miscco 

The issue is even though i added directories for cuda and linked "cuda" and "cuda-10.2" (which is currently installed one) Jetson Nano (for which as you flash JetPack, you get CUDA installed) failing to find the installed cuda in the system.

**Comment by miscco** [comment]
Just to be clear, we are the cccl project. 

Our libraries cub, thrust and libcu++ are used to develop c++ programs using cuda. We are indeed packaged with the cuda toolchain, but we have no business regarding its installation.

For jetson Nano, I can only refer you to the official site https://developer.nvidia.com/embedded/learn/get-started-jetson-nano-devkit

**Comment by jarmak-nv** [comment]
Hey @mericgeren 

You may find better success if you post a question on the Jetson Dev Forums here: https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76

Quick digging into your links also pointed me here https://github.com/Qengineering/Jetson-Nano-image where they provide an image that might get you started quickly. They are probably better equipped to help you as well.

I hope you can resolve the issue - good luck!
