### ISSUE TITLE
[BUG]: Re-enable flaky barrier_parity tests 

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#511]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Runtime Error

### Component

libcu++

### Describe the bug

Our heterogeneous tests have been notoriously flaky in the recent month. We need to make sure that they are sound and performing as expected. 

Continuously restarting CI for every PR is not an option

### How to Reproduce

Essentially most CI runs failed with at least one of those tests failing

### Expected behavior

Tests should never hang

**Comment by jrhemstad** [comment]
@miscco can you provide a link to which tests are disabled that we'd like to be able to re-enable?

**Comment by miscco** [comment]
We disabled the two barrier parity tests
```
barrier_parity.cuda.pass.cpp
barrier_parity.std.pass.cpp
```
