### ISSUE TITLE
[FEA]: Inconsistent template parameter in `thrust::complex` operators

### ISSUE THREAD

**Issue by srinivasyadav18** [NVIDIA/cccl#554]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

Thrust

### Is your feature request related to a problem? Please describe.

The template parameter in `thrust::complex` operators w.r.t to the arguments are in consistently used.
For instance - 
```cpp
template <typename T0, typename T1>
__host__ __device__ typename detail::disable_if<
  detail::or_<detail::is_same<T0, T1>, detail::not_<detail::is_arithmetic<T1>>>::value,
  complex<typename detail::promoted_numerical_type<T0, T1>::type>>::type
operator-(const T0 &x, const complex<T1> &y);
```
The type `T1` should actually be `T0`.

### Describe the solution you'd like

Replalce T1 with T0 in `detail::is_arithmetic<T0>`
```cpp
template <typename T0, typename T1>
__host__ __device__ typename detail::disable_if<
  detail::or_<detail::is_same<T0, T1>, detail::not_<detail::is_arithmetic<T0>>>::value,
  complex<typename detail::promoted_numerical_type<T0, T1>::type>>::type
operator-(const T0 &x, const complex<T1> &y);
```

**Comment by jrhemstad** [comment]
Thanks @srinivasyadav18. Are you still thinking you'd like to take care of this?

**Comment by srinivasyadav18** [comment]
@jrhemstad Yes. I have a PR coming up right-away.
