### ISSUE TITLE
[FEA]: Consolidate logic for compiler detection 

### ISSUE THREAD

**Issue by miscco** [NVIDIA/cccl#572]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

With cub, thrust and libcu++ being three different libraries we have a ton of duplicated code. 

We want to incrementally move that code into common headers, so that we do not need to repeat it and also only have one pace to fix if changes need to be made

One glaring occurrence of that duplication  is the way we determine which host / device compiler is used. 

With the #531 we are getting a unified config that we can use in all libraries and also convenient definitions for 
`_CCCL_COMPILER_{GCC, CLANG, MSVC, NVHPC, NVRTC}`

### Describe the solution you'd like

We should clean up all existing uses of 
`_LIBCUDACXX_COMPILER_{GCC, CLANG, MSVC, NVHPC, NVRTC}`
`THRUST_HOST_COMPILER_{GCC, CLANG, MSVC, INTEL}`
`CUB_HOST_COMPILER_{GCC, CLANG, MSVC, INTEL}`

**Comment by Yaraslaut** [comment]
Hi, I would like to work on this issue, could you please assign it to me?

**Comment by miscco** [comment]
Thanks a lot. I assigned you
