### ISSUE TITLE
[BUG]: `cub::DeviceMemcpy::Batched` cannot copy from const source pointers

### ISSUE THREAD

**Issue by fkallen** [NVIDIA/cccl#586]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Compile-time Error

### Component

CUB

### Describe the bug

`cub::DeviceMemcpy::Batched` does not compile with const source pointers, for example `const char** `

```
/opt/compiler-explorer/libs/cccl/trunk/cub/cub/agent/agent_batch_memcpy.cuh(863): error: a value of type "const char *" cannot be assigned to an entity of type "void *"
          blev_buffer_srcs[tile_buffer_offset + blev_buffer_offset] =
```

### How to Reproduce

```
#include <cub/cub.cuh>

int main()
{
    size_t tmpbytes = 0;
    cub::DeviceMemcpy::Batched(
        nullptr,
        tmpbytes,
        (const char**)nullptr,
        (char**)nullptr,
        (int*)nullptr,
        0
    );
    return 0;
}
```

### Expected behavior

It should work with const pointers

### Reproduction link

https://godbolt.org/z/fW6qshTPE

**Comment by elstehle** [comment]
Thanks for reporting the issue, @fkallen . I'll look into this.

**Comment by ZelboK** [comment]
Hi, can I pick this up? @elstehle

**Comment by elstehle** [comment]
Yes, sure, your help would be greatly appreciated, @ZelboK!

**Comment by ttnghia** [comment]
Oh I'm about to file this issue, but found that it was filed by somebody else.

Is there any progress on this, after a year of work?

**Comment by ZelboK** [comment]
> Oh I'm about to file this issue, but found that it was filed by somebody else.
> 
> Is there any progress on this?

I forgot about this issue and haven't done any work on it. Will not be able to commit either. Not sure about @elstehle though.

**Comment by elstehle** [comment]
Thank you for following up on this, @ZelboK. No problem, if you don't find the time to work on this. I can take this over.
