### ISSUE TITLE
[FEA]: Ability to add compiler flags to CI scripts as args.

### ISSUE THREAD

**Issue by ZelboK** [NVIDIA/cccl#589]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

General CCCL

### Is your feature request related to a problem? Please describe.

I think it would be really nice to be able to pass flags as arguments to the CI script. 

For example, since Thrust has a lot of template heavy code, it would be nice to limit errors at 1 to prevent template explosions.

### Describe the solution you'd like

 I usually achieve this myself by manually adding the following lines to `build_common.sh` when I need it. 

```
readonly CXX_FLAGS="-Wfatal-errors"
readonly CUDA_HOST_FLAGS="-Wfatal-errors"
```

Albeit I have not tried this with the new CI scripts yet to see if it still works. I'd be surprised if it didn't. I don't have enough time to look into the CI scripts to see what would be the best way to intervene for this so I'll have to leave that to someone else on how to solve.

**Comment by wmaxey** [comment]
We also need something like this for lit additional flags. We cannot currently produce machine readable logs with `-o output.json` with the ctest preset.
