### ISSUE TITLE
[FEA]: Avoid relative includes

### ISSUE THREAD

**Issue by gevtushenko** [NVIDIA/cccl#631]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

CUB

### Is your feature request related to a problem? Please describe.

As part of the CUB style guide, we were getting away from using relative includes. Currently, project is in the inconsistent state in regard to CUB headers inclusion. 

### Describe the solution you'd like

We should get rid of remaining relative includes.

**Comment by leofang** [comment]
Thanks, @gevtushenko for leading the effort! Highly appreciated.

@jrhemstad Can we please reopen this issue to track Thrust/CCCL needs? In particular, @miscco noted offline the following comments
> Urgh, from a libcu++ side this is going to be exceptionally painfull
> Currently we have relational includes like
> #include "../__type_traits/void_t.h"
> The issue is that we are a fork of libc++, so doing
> #include <__type_traits/void_t.h>
> Will find the libc++ standard header. So what we would have to do is change this to:
> #include <cuda/std/detail/libcxx/include/__type_traits/void_t.h>
> I am really not looking forward to this

> I mean, it is a search and replace issue, and I am totally willing to suffer some long file names if it helps our users

**Comment by jrhemstad** [comment]
@leofang here you go! https://github.com/NVIDIA/cccl/issues/641
