### ISSUE TITLE
[BUG]: Unfavourable interaction between thrust::sort and thrust::sort_by_key

### ISSUE THREAD

**Issue by mvieth** [NVIDIA/cccl#655]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this bug and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Type of Bug

Silent Failure

### Component

Not sure

### Describe the bug

I noticed that `thrust::sort_by_key` fails/gives a wrong result in a very specific circumstance, namely:
- `thrust::sort_by_key` is used in a shared library, let's say library A
- `thrust::sort` is used in a second shared library, let's say library B
- both are linked to the main program
- `thrust::sort_by_key` is called with more than 4864 elements (threshold for selecting specific sorting algorithm)

With git bisect, I determined that this problem occurs since https://github.com/NVIDIA/cub/commit/c4299c46fdf88654f23a7c01dca3bc4c2976bb7a , meaning that all thrust/cub 2.x.y versions are affected, but 1.x.y versions are fine.
The problem occurs with GCC under Linux, but not with MSVC under Windows.
When I run it with `compute-sanitizer`, it shows `Program hit cudaErrorMissingConfiguration (error 52) due to "__global__ function call is not configured" on CUDA API call to cudaGetLastError` for `histogram_kernel` and `exclusive_sum_kernel`.
My best guess what happens: some symbols in library A and library B get confused during linking, possibly because some functions (like `DeviceRadixSortExclusiveSumKernel`) don't have `ValueT` in their template parameter list (which is `cub::NullType` for `thrust::sort` and something else for `thrust::sort_by_key`).
This might happen with other thrust functions (unconfirmed but possible, I think).
This bug was first noticed in https://github.com/PointCloudLibrary/pcl/issues/5846

### How to Reproduce

Here is a minimal reproducible example: [thrust_test.zip](https://github.com/NVIDIA/cccl/files/13249157/thrust_test.zip)

### Expected behavior

`thrust::sort_by_key` always give the correct result (sorted)

### Operating System

Linux (exact version or distro does not matter)

### nvidia-smi output

Not relevant for the problem, as far as I can tell

### NVCC version

Not relevant, but thrust/cub must be version 2.0.0 or newer (as described above)

**Comment by gevtushenko** [comment]
@mvieth thank you for reporting the issue! It should've been addressed by https://github.com/NVIDIA/cccl/pull/443. Could you please try CCCL/main to see if you still can reproduce it?

**Comment by mvieth** [comment]
@gevtushenko Yes, that solves it. Thanks!
