### ISSUE TITLE
_LIBCUDACXX_CUDACC_VER  is not defined correctly when compiled with clang

### ISSUE THREAD

**Issue by Artem-B** [NVIDIA/cccl#670]
https://github.com/NVIDIA/cccl/blob/bd58bb5c4c883c81e878def3502d47593daebe8b/libcudacxx/include/cuda/std/detail/libcxx/include/__config#L60

Clang does not define `__CUDACC_VER_{MAJOR,MINOR,BUILD}__` and libcu++ ends up with incorrectly defined `_LIBCUDACXX_CUDACC_VER` and various other knobs that depend on it.

Clang version numbers, if clang were to set `__CUDACC_VER...`,  would not make a whole lot of sense for the code checking for NVCC versions. Perhaps in case of compilation with clang, `_LIBCUDACXX_CUDACC_VER` should be derived from CUDA_VERSION instead? I can get clang to do it automatically, but we'll still need to deal with clang binaries out there in the wild that will not have the `__CUDACC_VER...` macros defined and they will be around for a while yet.

Bonus points for defining feature knobs based on the features themselves, not on the CUDA SDK version, as support for a particular feature (like builtins) will not always be directly tied to the CUDA version, when we're compiling with clang. E.g. some builtins introduced in CUDA SDK X, may not be available in clang right away, and vice versa, clang may support some C++ features, even if NVCC in that particular CUDA release didn't.

**Comment by jrhemstad** [comment]
Filed https://github.com/NVIDIA/cccl/issues/671
