### ISSUE TITLE
[FEA]: Make `_LIBCUDACXX_CUDACC_VER` unique to nvcc

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#671]
### Is this a duplicate?

- [X] I confirmed there appear to be no [duplicate issues](https://github.com/NVIDIA/cccl/issues) for this request and that I agree to the [Code of Conduct](CODE_OF_CONDUCT.md)

### Area

libcu++

### Is your feature request related to a problem? Please describe.

libcu++ defines `_LIBCUDACXX_CUDACC_VER` macros based on `__CUDACC_VER*` if `_CUDACC_` is defined.

When compiling with `nvcc`, this means `_LIBCUDACXX_CUDACC_VER` just encodes the `nvcc` version used for compilation. 

https://github.com/NVIDIA/cccl/blob/bd58bb5c4c883c81e878def3502d47593daebe8b/libcudacxx/include/cuda/std/detail/libcxx/include/__config#L58-L71

However, this does not work with `clang`. `clang` defines `_CUDACC_` but does not define `__CUDACC_VER_*`. So the `_LIBCUDACXX_CUDACC_VER` macros will be empty. 

### Describe the solution you'd like

Rename `_LIBCUDACXX_CUDACC_VER` to `_LIBCUDACXX_NVCC_VER` since it is only relevant for `nvcc`.

Furthermore, `_LIBCUDACXX_NVCC_VER` should only be defined when `_LIBCUDACXX_COMPILER_NVCC` is also defined.

**Comment by miscco** [comment]
This has been fixed recently
