### ISSUE TITLE
Migrate cccl_devcontainers matrix to rapidsai/devcontainers

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/cccl#72]
@trxcllnt originally created github.com/nvidia/cccl_devcontainers to host the devcontainers for our CI and local dev. This was based on work he originally did in https://github.com/rapidsai/devcontainers to define similar devcontainers for RAPIDS CI and local dev.

However, we have since realized that we don't need `cccl_devcontainers` as a separate repo and we would like to just expand the set of features in `rapidsai/devcontainers` to include the features needed for CCCL. 

One important difference between `cccl_devcontainers` and `rapidsai/devcontainers` is the method for specifying the matrix of container images. `cccl_devcontainers` uses a single [yaml file](https://github.com/NVIDIA/cccl_devcontainers/blob/c8dbef88527b7bb3a17d01620dc2eb7f70f859ad/matrix.yml) to define the matrix of containers and their associated features. In contrast, the `rapidsai/devcontainers` requires creating a [separate directory](https://github.com/rapidsai/devcontainers/tree/branch-23.06/images) for each combination of features into an image.

We would like to refactor the `rapidsai/devcontainers` implementation to use the same style of yaml file image matrix specification as was used in `cccl_devcontainers`. 

We also want to preserve the functionality in `rapidsai/devcontainers` that is intelligent about testing/rebuilding containers only when their constituent features have changed. `cccl_devcontainers` did not have this functionality. 

```[tasklist]
### Tasks
- [x] Extract inline bash scripts into separate, testable bash script files
- [x] Update rapidsai container matrix with CCCL devcontainer requirements
```

**Comment by jrhemstad** [comment]
Paul's PR: https://github.com/trxcllnt/devcontainers/pull/4

**Comment by trxcllnt** [comment]
https://github.com/rapidsai/devcontainers/pull/70
