### ISSUE TITLE
Improve Open-Source Contribution Process

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cccl#735]
As some of you have noticed, the Thrust and CUB repositories have been going through a lot of changes recently. These have been aimed at improving our open-source contribution process and transitioning our internal development processes to be carried out in the open whenever possible.

A major part of that plan involves migrating our continuous integration testing away from NVIDIA's internal systems and into the open. Additionally, we need to simplify the process of integrating changes from our open-source Github repositories into NVIDIA's internal git and perforce repositories. Automating these processes is complicated for many reasons and will take some time to complete, but they are currently high priority goals for the team.

Currently, it is a rather tedious process to take open-source contributions, test them internally, review them, and integrate them into our public and private repositories. There are a lot of manual steps involved that make it far more difficult than it should be to simply land a PR.

However, once we have open, easy-to-use CI and integration automation in place it will be much easier for us to land your patches. This will allow us to start working through the backlog of pull requests and be more responsive to our open-source contributors. 

As things evolve, we'll keep this issue updated.

**Comment by jrhemstad** [comment]
I'm going to call this resolved by our new contributor guide: https://github.com/NVIDIA/cccl/blob/main/CONTRIBUTING.md
