### ISSUE TITLE
Switch to `cuda::std::tuple`/`<cuda/std/tuple>`

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/cccl#742]
### Original Comment

Note that this requires us to sort out fetching the libcu++ headers in Thrust/CUB internal builds.

### 2022-04-26: @allisonvacanti Update

The libcu++ dependency will be merged soon for 2.0 (PR: NVIDIA/thrust#1605). Afterwards, we'll be able to start looking into this:

* [ ] Run metabench study to test the difference in compile times between equivalent uses of `cuda::std::tuple` and the current `thrust::tuple`.
* [ ] Scope out feasibility. Replace the current tuple with `template <typename ...T> using tuple = cuda::std::tuple<T...>`. Take note of what breaks and estimate how much effort it will be to fix. See the discussion of `tuple_of_iterator_references` below for a known trouble spot.

This information will let us make a better informed prioritization.

**Comment by jrhemstad** [comment]
closed by https://github.com/NVIDIA/cccl/pull/262
