### ISSUE TITLE
[BUG] `ci/local/build.bash` failed when `CUDA_VISIBLE_DEVICES` is set to multiple devices

### ISSUE THREAD

**Issue by daxiongshu** [NVIDIA/cccl#805]
`ci/local/build.bash` failed when `CUDA_VISIBLE_DEVICES` is set. The error message is:
```
Digest: sha256:c5c1f5e1534287be3fa48a0896c40b470cfc76abfd6ba6505c437cf131802663
Status: Downloaded newer image for gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9
docker.io/gpuci/cccl:cuda11.5.1-devel-ubuntu20.04-gcc9
docker: Error response from daemon: cannot set both Count and DeviceIDs on device request.
```
The error occurs when `CUDA_VISIBLE_DEVICES` is set to all GPUs or a subset of all GPUs. For example, `export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7` on a 8-GPU machine still triggers the error. The only workaround I know is to unset `CUDA_VISIBLE_DEVICE`

**Comment by jrhemstad** [comment]
This infrastructure has been completely replaced. See https://github.com/NVIDIA/cccl/blob/main/CONTRIBUTING.md
