### ISSUE TITLE
Make cub NVRTC-compatible

### ISSUE THREAD

**Issue by l0calh05t** [NVIDIA/cccl#851]
Currently, cub includes a number of system headers causing errors such as

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vadefs.h(143): error: A function without execution space annotations (__host__/__device__/__global__) is considered a host function, and host functions are not allowed in JIT mode. Consider using -default-device flag to process unannotated functions as __device__ functions in JIT mode

when attempting to use cub with NVRTC. It would be great if cub could be modified to also support use in NVRTC. (Pointers only instead of general iterators would be fine for me).

Note: while passing `-default-device` to NVRTC removes this particular error, other errors such as

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(81): error: identifier "push" is undefined

or 

> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vcruntime.h(81): error: this declaration has no storage class or type specifier

remain. Furthermore, packaging all compiler headers is not feasible anyways.

**Comment by jrhemstad** [comment]
closing in favor of https://github.com/NVIDIA/cccl/issues/403
