### ISSUE TITLE
BlockRadixSort and arrangement of input data

### ISSUE THREAD

**Issue by sploner** [NVIDIA/cccl#857]
Sorry if I'm missing the obvious point, but:
- The [documentation for BlockRadixSort](https://nvlabs.github.io/cub/classcub_1_1_block_radix_sort.html#pub-methods) divides the sorting methods in purely "blocked arrangements" and "blocked arrangement -> striped arrangement".
- Another quote: "Performs an ascending block-wide radix sort over a blocked arrangement of keys."
- It even suggests how to get data in blocked arrangement by referring to "Consider variants of cub::BlockLoad for efficiently gathering a blocked arrangement of elements across threads."
After reading all this I captured myself in doing a BlockExchange to go from striped to blocked. But wait.

It's obvious that we need to distinguish the output's arrangement.
But why would we care about the input data's arrangement? There is no thing like "valid_items" where we'd need to care which ones are the first N items. All input items are sorted, thus if sorting works, the result is independant of the input arrangement.

So why does the documentation request a blocked arrangement?

**Comment by pauleonix** [comment]
I would guess that is is documented for use-cases where a stability is needed. If you are not interested in the stability of radix sort, you do not need to care about the input arrangement.

**Comment by gevtushenko** [comment]
@sploner you are right, there are cases when input arrangement doesn't matter. For instance, if you sort keys using all bits, there's no way to understand if the input was in striped or blocked arrangement. Nevertheless, as @pauleonix rightfully noted, the documentation impacts cases that rely on stability. Stability only makes sense when there's a payload. For instance, if you sort keys using only some bits, you'll get different results depending on striped or blocked input arrangement. Same is true when you sort pairs (keys and values).
