### ISSUE TITLE
Decide godbolt strategy for CCCL monorepo

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cccl#91]
We may want to leave the libcu++ and Thrust/CUB libraries divided in the UI, but update the logic to pull the CCCL repo and configure the `find_package` calls to only bring in the requested targets and their dependencies.

Or we might want to have a single CCCL library listed on godbolt. This would be kinda problematic for a couple of reasons -- the old, pre-monorepo versions would be unavailable (or listed as separate libraries) in the CE UI, and users are less likely to recognize "CCCL" vs the project names, impacting discoverability.

**Comment by jrhemstad** [comment]
In https://github.com/compiler-explorer/compiler-explorer/pull/5477 I added a new "CUDA C++ Core Libraries" entry and added a note to the existing CCCL libs that they are legacy and should use the new one instead.
