### ISSUE TITLE
Update versions of projects available on godbolt

### ISSUE THREAD

**Issue by allisonvacanti** [NVIDIA/cccl#92]
The Thrust/CUB libraries are missing the last few tags on godbolt, and libcu++ only provides a nightly snapshot. We should backfill tagged libcu++ versions and catch up Thrust/CUB.

Updating CE involves modifying two files in two PRs to repos in the Compiler Explorer github org. I've documented the process here: https://nvidia.github.io/thrust/contributing/release_process.html#update-compiler-explorer

**Comment by jrhemstad** [comment]
Closed by https://github.com/compiler-explorer/compiler-explorer/pull/5477
