### ISSUE TITLE
Get ninja build log trace for CUB

### ISSUE THREAD

**Issue by elstehle** [NVIDIA/cccl#96]
CUB tests take quite some time to compile. Having a break down on the time spent on individual tests may help guide efforts to (further) split up large and long-running translation units.

**Comment by elstehle** [comment]
It looks like radix sort tests are the most dominant. Note that radix sort has already been split up into multiple translation units. Segmented sort seems to be the longest running translation unit.

![CUB build trace](https://github.com/NVIDIA/cccl/assets/3958403/bf185bb1-06f5-4c90-b642-969256683846)

tarball containing `trace.json` and the `png`:
[trace.tar.gz](https://github.com/NVIDIA/cccl/files/11616353/trace.tar.gz)

**Comment by jrhemstad** [comment]
I'd definitely try and focus on porting the radix sort and segmented sort and splitting them up to help improve build parallelism.
