### ISSUE TITLE
Add `cuda::std::variant`, `cuda::std::visit`, and `cuda::std::monostate`

### ISSUE THREAD

**Issue by aschaffer** [NVIDIA/cccl#981]
It would be helpful to have discriminated union functionality, equivalent to C++17 standard `std::variant`, `std::visit`, `std::monostate`, but available in device code. 

See a nice summary of that functionality, for example, in "C++17, The Complete Guide", by N. Josuttis, 2019, Chapter 16.

**Comment by ajpowelsnl** [comment]
Hi @mhoemmen - HNY!  Do we have a `cuda::std::variant` merged 😄

**Comment by mhoemmen** [comment]
@ajpowelsnl Greetings! : - D  

> Do we have a cuda::std::variant merged

Yes, indeed!  libcu++ has a `cuda::std::variant`.

https://github.com/NVIDIA/cccl/blob/main/libcudacxx/include/cuda/std/variant
