### ISSUE TITLE
Feature: clang CUDA (device compilation) support

### ISSUE THREAD

**Issue by MatthiasKohl** [NVIDIA/cccl#991]
This issue is similar to this one in cuCollections: https://github.com/NVIDIA/cuCollections/issues/128

While working on RAFT (primitives for RADPIS, PR: https://github.com/rapidsai/raft/pull/424), I noticed that libcudacxx doesn't support having its device code compiled with clang.

It would be great to support this, if possible.
If test coverage is good enough, it's usually good enough to simply transform `nvcc` commands to clang for which I have a somewhat usable script in the above mentioned PR for RAFT, and apply those commands to the entire test suite.

**Comment by jrhemstad** [comment]
closed by https://github.com/NVIDIA/cccl/pull/493
