### ISSUE TITLE
Unexpected types for some climits constants under __CUDACC_RTC__

### ISSUE THREAD

**Issue by benbarsdell** [NVIDIA/cccl#994]
For example, this fails:
`static_assert(std::is_same<decltype(ULLONG_MAX), unsigned long long>::value, "");`
(`ULLONG_MAX` is actually `unsigned long`).

https://github.com/NVIDIA/libcudacxx/blob/4a458fe/include/cuda/std/climits#L46-L47

There may also be an issue on 32-bit systems with this:
https://github.com/NVIDIA/libcudacxx/blob/4a458fe/include/cuda/std/climits#L42-L43

These are the only problematic cases I've noticed, but the way the constants are defined (hex literals without suffixes) makes it hard to tell if there are other issues too.

**Comment by miscco** [comment]
I believe this has been fixed
